// src/app.ts
import express9 from "express";

// src/modules/provider/provider.router.ts
import express from "express";

// src/lib/prisma.ts
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";

// generated/prisma/client.ts
import * as path from "path";
import { fileURLToPath } from "url";

// generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.4.1",
  "engineVersion": "55ae170b1ced7fc6ed07a15f110549408c501bb3",
  "activeProvider": "postgresql",
  "inlineSchema": '// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\n// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?\n// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init\n\ngenerator client {\n  provider = "prisma-client"\n  output   = "../generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nmodel Provider_Profile {\n  id              String  @id @default(uuid())\n  is_active       Boolean @default(true)\n  user_id         String  @unique\n  user            User    @relation(fields: [user_id], references: [id])\n  restaurant_name String  @db.VarChar(150)\n  address         String  @db.VarChar(250)\n  contact_number  String\n  image           String?\n  meals           Meals[]\n\n  @@index([user_id])\n}\n\nmodel Orders {\n  id          String @id @default(uuid())\n  customer_id String\n\n  delivery_address String\n  total_price      Decimal       @db.Decimal(10, 2)\n  status           OrderStatus   @default(PLACED)\n  created_at       DateTime      @default(now())\n  orderItems       Order_items[]\n\n  @@index([customer_id])\n}\n\nenum OrderStatus {\n  PLACED\n  PREPARING\n  READY\n  DELIVERED\n  CANCELLED\n}\n\nmodel Meals {\n  id          String           @id @default(uuid())\n  provider_id String\n  provider    Provider_Profile @relation(fields: [provider_id], references: [id])\n  category_id String\n  category    Categories       @relation(fields: [category_id], references: [id])\n  name        String           @db.VarChar(100)\n  status      MealsStatus      @default(AVAILABLE)\n  description String           @db.Text\n  price       Decimal          @db.Decimal(10, 2)\n  image_url   String\n  reviews     reviews[]\n  orderItems  Order_items[]\n\n  @@index([provider_id])\n}\n\nenum MealsStatus {\n  AVAILABLE\n  UNAVAILABLE\n}\n\nmodel Categories {\n  id    String  @id @default(uuid())\n  name  String  @db.VarChar(150)\n  meals Meals[]\n}\n\nmodel Order_items {\n  id             String  @id @default(uuid())\n  customer_id    String\n  customer       User    @relation(fields: [customer_id], references: [id])\n  meal_id        String\n  meal           Meals   @relation(fields: [meal_id], references: [id])\n  quantity       Int\n  price_at_order Decimal @db.Decimal(10, 2)\n  orders         Orders? @relation(fields: [ordersId], references: [id])\n  ordersId       String?\n\n  @@index([customer_id])\n  @@index([meal_id])\n}\n\nmodel reviews {\n  id          String   @id @default(uuid())\n  customer_id String\n  customer    User     @relation(fields: [customer_id], references: [id])\n  meal_id     String\n  meal        Meals    @relation(fields: [meal_id], references: [id])\n  rating      Int\n  comment     String\n  created_at  DateTime @default(now())\n\n  @@index([customer_id])\n}\n\nmodel User {\n  id              String            @id\n  name            String\n  email           String\n  emailVerified   Boolean           @default(false)\n  image           String?\n  createdAt       DateTime          @default(now())\n  updatedAt       DateTime          @updatedAt\n  sessions        Session[]\n  accounts        Account[]\n  orderItems      Order_items[]\n  reviews         reviews[]\n  providerProfile Provider_Profile?\n\n  role   UserRole @default(USER)\n  phone  String?\n  status String?  @default("ACTIVE")\n\n  @@unique([email])\n  @@map("user")\n}\n\nenum UserRole {\n  USER\n  ADMIN\n  PROVIDER\n}\n\nmodel Session {\n  id        String   @id\n  expiresAt DateTime\n  token     String\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  ipAddress String?\n  userAgent String?\n  userId    String\n  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  @@unique([token])\n  @@index([userId])\n  @@map("session")\n}\n\nmodel Account {\n  id                    String    @id\n  accountId             String\n  providerId            String\n  userId                String\n  user                  User      @relation(fields: [userId], references: [id], onDelete: Cascade)\n  accessToken           String?\n  refreshToken          String?\n  idToken               String?\n  accessTokenExpiresAt  DateTime?\n  refreshTokenExpiresAt DateTime?\n  scope                 String?\n  password              String?\n  createdAt             DateTime  @default(now())\n  updatedAt             DateTime  @updatedAt\n\n  @@index([userId])\n  @@map("account")\n}\n\nmodel Verification {\n  id         String   @id\n  identifier String\n  value      String\n  expiresAt  DateTime\n  createdAt  DateTime @default(now())\n  updatedAt  DateTime @updatedAt\n\n  @@index([identifier])\n  @@map("verification")\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"Provider_Profile":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"is_active","kind":"scalar","type":"Boolean"},{"name":"user_id","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"Provider_ProfileToUser"},{"name":"restaurant_name","kind":"scalar","type":"String"},{"name":"address","kind":"scalar","type":"String"},{"name":"contact_number","kind":"scalar","type":"String"},{"name":"image","kind":"scalar","type":"String"},{"name":"meals","kind":"object","type":"Meals","relationName":"MealsToProvider_Profile"}],"dbName":null},"Orders":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"customer_id","kind":"scalar","type":"String"},{"name":"delivery_address","kind":"scalar","type":"String"},{"name":"total_price","kind":"scalar","type":"Decimal"},{"name":"status","kind":"enum","type":"OrderStatus"},{"name":"created_at","kind":"scalar","type":"DateTime"},{"name":"orderItems","kind":"object","type":"Order_items","relationName":"Order_itemsToOrders"}],"dbName":null},"Meals":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"provider_id","kind":"scalar","type":"String"},{"name":"provider","kind":"object","type":"Provider_Profile","relationName":"MealsToProvider_Profile"},{"name":"category_id","kind":"scalar","type":"String"},{"name":"category","kind":"object","type":"Categories","relationName":"CategoriesToMeals"},{"name":"name","kind":"scalar","type":"String"},{"name":"status","kind":"enum","type":"MealsStatus"},{"name":"description","kind":"scalar","type":"String"},{"name":"price","kind":"scalar","type":"Decimal"},{"name":"image_url","kind":"scalar","type":"String"},{"name":"reviews","kind":"object","type":"reviews","relationName":"MealsToreviews"},{"name":"orderItems","kind":"object","type":"Order_items","relationName":"MealsToOrder_items"}],"dbName":null},"Categories":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"meals","kind":"object","type":"Meals","relationName":"CategoriesToMeals"}],"dbName":null},"Order_items":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"customer_id","kind":"scalar","type":"String"},{"name":"customer","kind":"object","type":"User","relationName":"Order_itemsToUser"},{"name":"meal_id","kind":"scalar","type":"String"},{"name":"meal","kind":"object","type":"Meals","relationName":"MealsToOrder_items"},{"name":"quantity","kind":"scalar","type":"Int"},{"name":"price_at_order","kind":"scalar","type":"Decimal"},{"name":"orders","kind":"object","type":"Orders","relationName":"Order_itemsToOrders"},{"name":"ordersId","kind":"scalar","type":"String"}],"dbName":null},"reviews":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"customer_id","kind":"scalar","type":"String"},{"name":"customer","kind":"object","type":"User","relationName":"UserToreviews"},{"name":"meal_id","kind":"scalar","type":"String"},{"name":"meal","kind":"object","type":"Meals","relationName":"MealsToreviews"},{"name":"rating","kind":"scalar","type":"Int"},{"name":"comment","kind":"scalar","type":"String"},{"name":"created_at","kind":"scalar","type":"DateTime"}],"dbName":null},"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"emailVerified","kind":"scalar","type":"Boolean"},{"name":"image","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"sessions","kind":"object","type":"Session","relationName":"SessionToUser"},{"name":"accounts","kind":"object","type":"Account","relationName":"AccountToUser"},{"name":"orderItems","kind":"object","type":"Order_items","relationName":"Order_itemsToUser"},{"name":"reviews","kind":"object","type":"reviews","relationName":"UserToreviews"},{"name":"providerProfile","kind":"object","type":"Provider_Profile","relationName":"Provider_ProfileToUser"},{"name":"role","kind":"enum","type":"UserRole"},{"name":"phone","kind":"scalar","type":"String"},{"name":"status","kind":"scalar","type":"String"}],"dbName":"user"},"Session":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"token","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"ipAddress","kind":"scalar","type":"String"},{"name":"userAgent","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"SessionToUser"}],"dbName":"session"},"Account":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"accountId","kind":"scalar","type":"String"},{"name":"providerId","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"AccountToUser"},{"name":"accessToken","kind":"scalar","type":"String"},{"name":"refreshToken","kind":"scalar","type":"String"},{"name":"idToken","kind":"scalar","type":"String"},{"name":"accessTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"refreshTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"scope","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"account"},"Verification":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"identifier","kind":"scalar","type":"String"},{"name":"value","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"verification"}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","orderBy","cursor","user","sessions","accounts","customer","provider","meals","_count","category","meal","reviews","orderItems","orders","providerProfile","Provider_Profile.findUnique","Provider_Profile.findUniqueOrThrow","Provider_Profile.findFirst","Provider_Profile.findFirstOrThrow","Provider_Profile.findMany","data","Provider_Profile.createOne","Provider_Profile.createMany","Provider_Profile.createManyAndReturn","Provider_Profile.updateOne","Provider_Profile.updateMany","Provider_Profile.updateManyAndReturn","create","update","Provider_Profile.upsertOne","Provider_Profile.deleteOne","Provider_Profile.deleteMany","having","_min","_max","Provider_Profile.groupBy","Provider_Profile.aggregate","Orders.findUnique","Orders.findUniqueOrThrow","Orders.findFirst","Orders.findFirstOrThrow","Orders.findMany","Orders.createOne","Orders.createMany","Orders.createManyAndReturn","Orders.updateOne","Orders.updateMany","Orders.updateManyAndReturn","Orders.upsertOne","Orders.deleteOne","Orders.deleteMany","_avg","_sum","Orders.groupBy","Orders.aggregate","Meals.findUnique","Meals.findUniqueOrThrow","Meals.findFirst","Meals.findFirstOrThrow","Meals.findMany","Meals.createOne","Meals.createMany","Meals.createManyAndReturn","Meals.updateOne","Meals.updateMany","Meals.updateManyAndReturn","Meals.upsertOne","Meals.deleteOne","Meals.deleteMany","Meals.groupBy","Meals.aggregate","Categories.findUnique","Categories.findUniqueOrThrow","Categories.findFirst","Categories.findFirstOrThrow","Categories.findMany","Categories.createOne","Categories.createMany","Categories.createManyAndReturn","Categories.updateOne","Categories.updateMany","Categories.updateManyAndReturn","Categories.upsertOne","Categories.deleteOne","Categories.deleteMany","Categories.groupBy","Categories.aggregate","Order_items.findUnique","Order_items.findUniqueOrThrow","Order_items.findFirst","Order_items.findFirstOrThrow","Order_items.findMany","Order_items.createOne","Order_items.createMany","Order_items.createManyAndReturn","Order_items.updateOne","Order_items.updateMany","Order_items.updateManyAndReturn","Order_items.upsertOne","Order_items.deleteOne","Order_items.deleteMany","Order_items.groupBy","Order_items.aggregate","reviews.findUnique","reviews.findUniqueOrThrow","reviews.findFirst","reviews.findFirstOrThrow","reviews.findMany","reviews.createOne","reviews.createMany","reviews.createManyAndReturn","reviews.updateOne","reviews.updateMany","reviews.updateManyAndReturn","reviews.upsertOne","reviews.deleteOne","reviews.deleteMany","reviews.groupBy","reviews.aggregate","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","User.upsertOne","User.deleteOne","User.deleteMany","User.groupBy","User.aggregate","Session.findUnique","Session.findUniqueOrThrow","Session.findFirst","Session.findFirstOrThrow","Session.findMany","Session.createOne","Session.createMany","Session.createManyAndReturn","Session.updateOne","Session.updateMany","Session.updateManyAndReturn","Session.upsertOne","Session.deleteOne","Session.deleteMany","Session.groupBy","Session.aggregate","Account.findUnique","Account.findUniqueOrThrow","Account.findFirst","Account.findFirstOrThrow","Account.findMany","Account.createOne","Account.createMany","Account.createManyAndReturn","Account.updateOne","Account.updateMany","Account.updateManyAndReturn","Account.upsertOne","Account.deleteOne","Account.deleteMany","Account.groupBy","Account.aggregate","Verification.findUnique","Verification.findUniqueOrThrow","Verification.findFirst","Verification.findFirstOrThrow","Verification.findMany","Verification.createOne","Verification.createMany","Verification.createManyAndReturn","Verification.updateOne","Verification.updateMany","Verification.updateManyAndReturn","Verification.upsertOne","Verification.deleteOne","Verification.deleteMany","Verification.groupBy","Verification.aggregate","AND","OR","NOT","id","identifier","value","expiresAt","createdAt","updatedAt","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","accountId","providerId","userId","accessToken","refreshToken","idToken","accessTokenExpiresAt","refreshTokenExpiresAt","scope","password","token","ipAddress","userAgent","name","email","emailVerified","image","UserRole","role","phone","status","every","some","none","customer_id","meal_id","rating","comment","created_at","quantity","price_at_order","ordersId","provider_id","category_id","MealsStatus","description","price","image_url","delivery_address","total_price","OrderStatus","is_active","user_id","restaurant_name","address","contact_number","is","isNot","connectOrCreate","upsert","disconnect","delete","connect","createMany","set","updateMany","deleteMany","increment","decrement","multiply","divide"]'),
  graph: "3AReoAEMAwAAzQIAIAgAAL8CACC4AQAAzAIAMLkBAAAgABC6AQAAzAIAMLsBAQAAAAHcAQEArgIAIfUBIACtAgAh9gEBAAAAAfcBAQCaAgAh-AEBAJoCACH5AQEAmgIAIQEAAAABACAMAwAAzQIAILgBAADZAgAwuQEAAAMAELoBAADZAgAwuwEBAJoCACG-AUAAmwIAIb8BQACbAgAhwAFAAJsCACHOAQEAmgIAIdYBAQCaAgAh1wEBAK4CACHYAQEArgIAIQMDAACeBAAg1wEAAN8CACDYAQAA3wIAIAwDAADNAgAguAEAANkCADC5AQAAAwAQugEAANkCADC7AQEAAAABvgFAAJsCACG_AUAAmwIAIcABQACbAgAhzgEBAJoCACHWAQEAAAAB1wEBAK4CACHYAQEArgIAIQMAAAADACABAAAEADACAAAFACARAwAAzQIAILgBAADXAgAwuQEAAAcAELoBAADXAgAwuwEBAJoCACG_AUAAmwIAIcABQACbAgAhzAEBAJoCACHNAQEAmgIAIc4BAQCaAgAhzwEBAK4CACHQAQEArgIAIdEBAQCuAgAh0gFAANgCACHTAUAA2AIAIdQBAQCuAgAh1QEBAK4CACEIAwAAngQAIM8BAADfAgAg0AEAAN8CACDRAQAA3wIAINIBAADfAgAg0wEAAN8CACDUAQAA3wIAINUBAADfAgAgEQMAAM0CACC4AQAA1wIAMLkBAAAHABC6AQAA1wIAMLsBAQAAAAG_AUAAmwIAIcABQACbAgAhzAEBAJoCACHNAQEAmgIAIc4BAQCaAgAhzwEBAK4CACHQAQEArgIAIdEBAQCuAgAh0gFAANgCACHTAUAA2AIAIdQBAQCuAgAh1QEBAK4CACEDAAAABwAgAQAACAAwAgAACQAgDAYAAM0CACALAADQAgAgDgAA1gIAILgBAADVAgAwuQEAAAsAELoBAADVAgAwuwEBAJoCACHkAQEAmgIAIeUBAQCaAgAh6QECAM8CACHqARAAyQIAIesBAQCuAgAhBAYAAJ4EACALAACfBAAgDgAAoQQAIOsBAADfAgAgDAYAAM0CACALAADQAgAgDgAA1gIAILgBAADVAgAwuQEAAAsAELoBAADVAgAwuwEBAAAAAeQBAQCaAgAh5QEBAJoCACHpAQIAzwIAIeoBEADJAgAh6wEBAK4CACEDAAAACwAgAQAADAAwAgAADQAgDwcAANMCACAKAADUAgAgDAAAswIAIA0AALICACC4AQAA0QIAMLkBAAAPABC6AQAA0QIAMLsBAQCaAgAh2QEBAJoCACHgAQAA0gLvASLsAQEAmgIAIe0BAQCaAgAh7wEBAJoCACHwARAAyQIAIfEBAQCaAgAhBAcAAOcDACAKAACgBAAgDAAA5gMAIA0AAOUDACAPBwAA0wIAIAoAANQCACAMAACzAgAgDQAAsgIAILgBAADRAgAwuQEAAA8AELoBAADRAgAwuwEBAAAAAdkBAQCaAgAh4AEAANIC7wEi7AEBAJoCACHtAQEAmgIAIe8BAQCaAgAh8AEQAMkCACHxAQEAmgIAIQMAAAAPACABAAAQADACAAARACABAAAADwAgCwYAAM0CACALAADQAgAguAEAAM4CADC5AQAAFAAQugEAAM4CADC7AQEAmgIAIeQBAQCaAgAh5QEBAJoCACHmAQIAzwIAIecBAQCaAgAh6AFAAJsCACECBgAAngQAIAsAAJ8EACALBgAAzQIAIAsAANACACC4AQAAzgIAMLkBAAAUABC6AQAAzgIAMLsBAQAAAAHkAQEAmgIAIeUBAQCaAgAh5gECAM8CACHnAQEAmgIAIegBQACbAgAhAwAAABQAIAEAABUAMAIAABYAIAMAAAALACABAAAMADACAAANACABAAAAFAAgAQAAAAsAIAoNAACyAgAguAEAAMgCADC5AQAAGwAQugEAAMgCADC7AQEAmgIAIeABAADKAvUBIuQBAQCaAgAh6AFAAJsCACHyAQEAmgIAIfMBEADJAgAhAQAAABsAIAMAAAALACABAAAMADACAAANACABAAAACwAgAwAAABQAIAEAABUAMAIAABYAIAwDAADNAgAgCAAAvwIAILgBAADMAgAwuQEAACAAELoBAADMAgAwuwEBAJoCACHcAQEArgIAIfUBIACtAgAh9gEBAJoCACH3AQEAmgIAIfgBAQCaAgAh-QEBAJoCACEBAAAAIAAgAQAAAAMAIAEAAAAHACABAAAACwAgAQAAABQAIAMAAAAPACABAAAQADACAAARACABAAAADwAgAQAAAAEAIAMDAACeBAAgCAAAggQAINwBAADfAgAgAwAAACAAIAEAACkAMAIAAAEAIAMAAAAgACABAAApADACAAABACADAAAAIAAgAQAAKQAwAgAAAQAgCQMAAJ0EACAIAACvAwAguwEBAAAAAdwBAQAAAAH1ASAAAAAB9gEBAAAAAfcBAQAAAAH4AQEAAAAB-QEBAAAAAQEVAAAtACAHuwEBAAAAAdwBAQAAAAH1ASAAAAAB9gEBAAAAAfcBAQAAAAH4AQEAAAAB-QEBAAAAAQEVAAAvADABFQAALwAwCQMAAJwEACAIAAD7AgAguwEBAN0CACHcAQEA4wIAIfUBIADvAgAh9gEBAN0CACH3AQEA3QIAIfgBAQDdAgAh-QEBAN0CACECAAAAAQAgFQAAMgAgB7sBAQDdAgAh3AEBAOMCACH1ASAA7wIAIfYBAQDdAgAh9wEBAN0CACH4AQEA3QIAIfkBAQDdAgAhAgAAACAAIBUAADQAIAIAAAAgACAVAAA0ACADAAAAAQAgHAAALQAgHQAAMgAgAQAAAAEAIAEAAAAgACAECQAAmQQAICIAAJsEACAjAACaBAAg3AEAAN8CACAKuAEAAMsCADC5AQAAOwAQugEAAMsCADC7AQEAkgIAIdwBAQCdAgAh9QEgAKYCACH2AQEAkgIAIfcBAQCSAgAh-AEBAJICACH5AQEAkgIAIQMAAAAgACABAAA6ADAhAAA7ACADAAAAIAAgAQAAKQAwAgAAAQAgCg0AALICACC4AQAAyAIAMLkBAAAbABC6AQAAyAIAMLsBAQAAAAHgAQAAygL1ASLkAQEAmgIAIegBQACbAgAh8gEBAJoCACHzARAAyQIAIQEAAAA-ACABAAAAPgAgAQ0AAOUDACADAAAAGwAgAQAAQQAwAgAAPgAgAwAAABsAIAEAAEEAMAIAAD4AIAMAAAAbACABAABBADACAAA-ACAHDQAAmAQAILsBAQAAAAHgAQAAAPUBAuQBAQAAAAHoAUAAAAAB8gEBAAAAAfMBEAAAAAEBFQAARQAgBrsBAQAAAAHgAQAAAPUBAuQBAQAAAAHoAUAAAAAB8gEBAAAAAfMBEAAAAAEBFQAARwAwARUAAEcAMAcNAACOBAAguwEBAN0CACHgAQAAjQT1ASLkAQEA3QIAIegBQADeAgAh8gEBAN0CACHzARAAhwMAIQIAAAA-ACAVAABKACAGuwEBAN0CACHgAQAAjQT1ASLkAQEA3QIAIegBQADeAgAh8gEBAN0CACHzARAAhwMAIQIAAAAbACAVAABMACACAAAAGwAgFQAATAAgAwAAAD4AIBwAAEUAIB0AAEoAIAEAAAA-ACABAAAAGwAgBQkAAIgEACAiAACLBAAgIwAAigQAIDQAAIkEACA1AACMBAAgCbgBAADEAgAwuQEAAFMAELoBAADEAgAwuwEBAJICACHgAQAAxQL1ASLkAQEAkgIAIegBQACTAgAh8gEBAJICACHzARAAugIAIQMAAAAbACABAABSADAhAABTACADAAAAGwAgAQAAQQAwAgAAPgAgAQAAABEAIAEAAAARACADAAAADwAgAQAAEAAwAgAAEQAgAwAAAA8AIAEAABAAMAIAABEAIAMAAAAPACABAAAQADACAAARACAMBwAAgAQAIAoAAKwDACAMAACtAwAgDQAArgMAILsBAQAAAAHZAQEAAAAB4AEAAADvAQLsAQEAAAAB7QEBAAAAAe8BAQAAAAHwARAAAAAB8QEBAAAAAQEVAABbACAIuwEBAAAAAdkBAQAAAAHgAQAAAO8BAuwBAQAAAAHtAQEAAAAB7wEBAAAAAfABEAAAAAHxAQEAAAABARUAAF0AMAEVAABdADAMBwAA_gMAIAoAAIkDACAMAACKAwAgDQAAiwMAILsBAQDdAgAh2QEBAN0CACHgAQAAhgPvASLsAQEA3QIAIe0BAQDdAgAh7wEBAN0CACHwARAAhwMAIfEBAQDdAgAhAgAAABEAIBUAAGAAIAi7AQEA3QIAIdkBAQDdAgAh4AEAAIYD7wEi7AEBAN0CACHtAQEA3QIAIe8BAQDdAgAh8AEQAIcDACHxAQEA3QIAIQIAAAAPACAVAABiACACAAAADwAgFQAAYgAgAwAAABEAIBwAAFsAIB0AAGAAIAEAAAARACABAAAADwAgBQkAAIMEACAiAACGBAAgIwAAhQQAIDQAAIQEACA1AACHBAAgC7gBAADAAgAwuQEAAGkAELoBAADAAgAwuwEBAJICACHZAQEAkgIAIeABAADBAu8BIuwBAQCSAgAh7QEBAJICACHvAQEAkgIAIfABEAC6AgAh8QEBAJICACEDAAAADwAgAQAAaAAwIQAAaQAgAwAAAA8AIAEAABAAMAIAABEAIAYIAAC_AgAguAEAAL4CADC5AQAAbwAQugEAAL4CADC7AQEAAAAB2QEBAJoCACEBAAAAbAAgAQAAAGwAIAYIAAC_AgAguAEAAL4CADC5AQAAbwAQugEAAL4CADC7AQEAmgIAIdkBAQCaAgAhAQgAAIIEACADAAAAbwAgAQAAcAAwAgAAbAAgAwAAAG8AIAEAAHAAMAIAAGwAIAMAAABvACABAABwADACAABsACADCAAAgQQAILsBAQAAAAHZAQEAAAABARUAAHQAIAK7AQEAAAAB2QEBAAAAAQEVAAB2ADABFQAAdgAwAwgAAPUDACC7AQEA3QIAIdkBAQDdAgAhAgAAAGwAIBUAAHkAIAK7AQEA3QIAIdkBAQDdAgAhAgAAAG8AIBUAAHsAIAIAAABvACAVAAB7ACADAAAAbAAgHAAAdAAgHQAAeQAgAQAAAGwAIAEAAABvACADCQAA8gMAICIAAPQDACAjAADzAwAgBbgBAAC9AgAwuQEAAIIBABC6AQAAvQIAMLsBAQCSAgAh2QEBAJICACEDAAAAbwAgAQAAgQEAMCEAAIIBACADAAAAbwAgAQAAcAAwAgAAbAAgAQAAAA0AIAEAAAANACADAAAACwAgAQAADAAwAgAADQAgAwAAAAsAIAEAAAwAMAIAAA0AIAMAAAALACABAAAMADACAAANACAJBgAAmwMAIAsAAMUDACAOAACcAwAguwEBAAAAAeQBAQAAAAHlAQEAAAAB6QECAAAAAeoBEAAAAAHrAQEAAAABARUAAIoBACAGuwEBAAAAAeQBAQAAAAHlAQEAAAAB6QECAAAAAeoBEAAAAAHrAQEAAAABARUAAIwBADABFQAAjAEAMAEAAAAbACAJBgAAmAMAIAsAAMMDACAOAACZAwAguwEBAN0CACHkAQEA3QIAIeUBAQDdAgAh6QECAJYDACHqARAAhwMAIesBAQDjAgAhAgAAAA0AIBUAAJABACAGuwEBAN0CACHkAQEA3QIAIeUBAQDdAgAh6QECAJYDACHqARAAhwMAIesBAQDjAgAhAgAAAAsAIBUAAJIBACACAAAACwAgFQAAkgEAIAEAAAAbACADAAAADQAgHAAAigEAIB0AAJABACABAAAADQAgAQAAAAsAIAYJAADtAwAgIgAA8AMAICMAAO8DACA0AADuAwAgNQAA8QMAIOsBAADfAgAgCbgBAAC5AgAwuQEAAJoBABC6AQAAuQIAMLsBAQCSAgAh5AEBAJICACHlAQEAkgIAIekBAgC2AgAh6gEQALoCACHrAQEAnQIAIQMAAAALACABAACZAQAwIQAAmgEAIAMAAAALACABAAAMADACAAANACABAAAAFgAgAQAAABYAIAMAAAAUACABAAAVADACAAAWACADAAAAFAAgAQAAFQAwAgAAFgAgAwAAABQAIAEAABUAMAIAABYAIAgGAACqAwAgCwAAugMAILsBAQAAAAHkAQEAAAAB5QEBAAAAAeYBAgAAAAHnAQEAAAAB6AFAAAAAAQEVAACiAQAgBrsBAQAAAAHkAQEAAAAB5QEBAAAAAeYBAgAAAAHnAQEAAAAB6AFAAAAAAQEVAACkAQAwARUAAKQBADAIBgAAqAMAIAsAALgDACC7AQEA3QIAIeQBAQDdAgAh5QEBAN0CACHmAQIAlgMAIecBAQDdAgAh6AFAAN4CACECAAAAFgAgFQAApwEAIAa7AQEA3QIAIeQBAQDdAgAh5QEBAN0CACHmAQIAlgMAIecBAQDdAgAh6AFAAN4CACECAAAAFAAgFQAAqQEAIAIAAAAUACAVAACpAQAgAwAAABYAIBwAAKIBACAdAACnAQAgAQAAABYAIAEAAAAUACAFCQAA6AMAICIAAOsDACAjAADqAwAgNAAA6QMAIDUAAOwDACAJuAEAALUCADC5AQAAsAEAELoBAAC1AgAwuwEBAJICACHkAQEAkgIAIeUBAQCSAgAh5gECALYCACHnAQEAkgIAIegBQACTAgAhAwAAABQAIAEAAK8BADAhAACwAQAgAwAAABQAIAEAABUAMAIAABYAIBIEAACwAgAgBQAAsQIAIAwAALMCACANAACyAgAgDwAAtAIAILgBAACsAgAwuQEAALYBABC6AQAArAIAMLsBAQAAAAG_AUAAmwIAIcABQACbAgAh2QEBAJoCACHaAQEAAAAB2wEgAK0CACHcAQEArgIAId4BAACvAt4BIt8BAQCuAgAh4AEBAK4CACEBAAAAswEAIAEAAACzAQAgEgQAALACACAFAACxAgAgDAAAswIAIA0AALICACAPAAC0AgAguAEAAKwCADC5AQAAtgEAELoBAACsAgAwuwEBAJoCACG_AUAAmwIAIcABQACbAgAh2QEBAJoCACHaAQEAmgIAIdsBIACtAgAh3AEBAK4CACHeAQAArwLeASLfAQEArgIAIeABAQCuAgAhCAQAAOMDACAFAADkAwAgDAAA5gMAIA0AAOUDACAPAADnAwAg3AEAAN8CACDfAQAA3wIAIOABAADfAgAgAwAAALYBACABAAC3AQAwAgAAswEAIAMAAAC2AQAgAQAAtwEAMAIAALMBACADAAAAtgEAIAEAALcBADACAACzAQAgDwQAAN4DACAFAADfAwAgDAAA4QMAIA0AAOADACAPAADiAwAguwEBAAAAAb8BQAAAAAHAAUAAAAAB2QEBAAAAAdoBAQAAAAHbASAAAAAB3AEBAAAAAd4BAAAA3gEC3wEBAAAAAeABAQAAAAEBFQAAuwEAIAq7AQEAAAABvwFAAAAAAcABQAAAAAHZAQEAAAAB2gEBAAAAAdsBIAAAAAHcAQEAAAAB3gEAAADeAQLfAQEAAAAB4AEBAAAAAQEVAAC9AQAwARUAAL0BADAPBAAA8QIAIAUAAPICACAMAAD0AgAgDQAA8wIAIA8AAPUCACC7AQEA3QIAIb8BQADeAgAhwAFAAN4CACHZAQEA3QIAIdoBAQDdAgAh2wEgAO8CACHcAQEA4wIAId4BAADwAt4BIt8BAQDjAgAh4AEBAOMCACECAAAAswEAIBUAAMABACAKuwEBAN0CACG_AUAA3gIAIcABQADeAgAh2QEBAN0CACHaAQEA3QIAIdsBIADvAgAh3AEBAOMCACHeAQAA8ALeASLfAQEA4wIAIeABAQDjAgAhAgAAALYBACAVAADCAQAgAgAAALYBACAVAADCAQAgAwAAALMBACAcAAC7AQAgHQAAwAEAIAEAAACzAQAgAQAAALYBACAGCQAA7AIAICIAAO4CACAjAADtAgAg3AEAAN8CACDfAQAA3wIAIOABAADfAgAgDbgBAAClAgAwuQEAAMkBABC6AQAApQIAMLsBAQCSAgAhvwFAAJMCACHAAUAAkwIAIdkBAQCSAgAh2gEBAJICACHbASAApgIAIdwBAQCdAgAh3gEAAKcC3gEi3wEBAJ0CACHgAQEAnQIAIQMAAAC2AQAgAQAAyAEAMCEAAMkBACADAAAAtgEAIAEAALcBADACAACzAQAgAQAAAAUAIAEAAAAFACADAAAAAwAgAQAABAAwAgAABQAgAwAAAAMAIAEAAAQAMAIAAAUAIAMAAAADACABAAAEADACAAAFACAJAwAA6wIAILsBAQAAAAG-AUAAAAABvwFAAAAAAcABQAAAAAHOAQEAAAAB1gEBAAAAAdcBAQAAAAHYAQEAAAABARUAANEBACAIuwEBAAAAAb4BQAAAAAG_AUAAAAABwAFAAAAAAc4BAQAAAAHWAQEAAAAB1wEBAAAAAdgBAQAAAAEBFQAA0wEAMAEVAADTAQAwCQMAAOoCACC7AQEA3QIAIb4BQADeAgAhvwFAAN4CACHAAUAA3gIAIc4BAQDdAgAh1gEBAN0CACHXAQEA4wIAIdgBAQDjAgAhAgAAAAUAIBUAANYBACAIuwEBAN0CACG-AUAA3gIAIb8BQADeAgAhwAFAAN4CACHOAQEA3QIAIdYBAQDdAgAh1wEBAOMCACHYAQEA4wIAIQIAAAADACAVAADYAQAgAgAAAAMAIBUAANgBACADAAAABQAgHAAA0QEAIB0AANYBACABAAAABQAgAQAAAAMAIAUJAADnAgAgIgAA6QIAICMAAOgCACDXAQAA3wIAINgBAADfAgAgC7gBAACkAgAwuQEAAN8BABC6AQAApAIAMLsBAQCSAgAhvgFAAJMCACG_AUAAkwIAIcABQACTAgAhzgEBAJICACHWAQEAkgIAIdcBAQCdAgAh2AEBAJ0CACEDAAAAAwAgAQAA3gEAMCEAAN8BACADAAAAAwAgAQAABAAwAgAABQAgAQAAAAkAIAEAAAAJACADAAAABwAgAQAACAAwAgAACQAgAwAAAAcAIAEAAAgAMAIAAAkAIAMAAAAHACABAAAIADACAAAJACAOAwAA5gIAILsBAQAAAAG_AUAAAAABwAFAAAAAAcwBAQAAAAHNAQEAAAABzgEBAAAAAc8BAQAAAAHQAQEAAAAB0QEBAAAAAdIBQAAAAAHTAUAAAAAB1AEBAAAAAdUBAQAAAAEBFQAA5wEAIA27AQEAAAABvwFAAAAAAcABQAAAAAHMAQEAAAABzQEBAAAAAc4BAQAAAAHPAQEAAAAB0AEBAAAAAdEBAQAAAAHSAUAAAAAB0wFAAAAAAdQBAQAAAAHVAQEAAAABARUAAOkBADABFQAA6QEAMA4DAADlAgAguwEBAN0CACG_AUAA3gIAIcABQADeAgAhzAEBAN0CACHNAQEA3QIAIc4BAQDdAgAhzwEBAOMCACHQAQEA4wIAIdEBAQDjAgAh0gFAAOQCACHTAUAA5AIAIdQBAQDjAgAh1QEBAOMCACECAAAACQAgFQAA7AEAIA27AQEA3QIAIb8BQADeAgAhwAFAAN4CACHMAQEA3QIAIc0BAQDdAgAhzgEBAN0CACHPAQEA4wIAIdABAQDjAgAh0QEBAOMCACHSAUAA5AIAIdMBQADkAgAh1AEBAOMCACHVAQEA4wIAIQIAAAAHACAVAADuAQAgAgAAAAcAIBUAAO4BACADAAAACQAgHAAA5wEAIB0AAOwBACABAAAACQAgAQAAAAcAIAoJAADgAgAgIgAA4gIAICMAAOECACDPAQAA3wIAINABAADfAgAg0QEAAN8CACDSAQAA3wIAINMBAADfAgAg1AEAAN8CACDVAQAA3wIAIBC4AQAAnAIAMLkBAAD1AQAQugEAAJwCADC7AQEAkgIAIb8BQACTAgAhwAFAAJMCACHMAQEAkgIAIc0BAQCSAgAhzgEBAJICACHPAQEAnQIAIdABAQCdAgAh0QEBAJ0CACHSAUAAngIAIdMBQACeAgAh1AEBAJ0CACHVAQEAnQIAIQMAAAAHACABAAD0AQAwIQAA9QEAIAMAAAAHACABAAAIADACAAAJACAJuAEAAJkCADC5AQAA-wEAELoBAACZAgAwuwEBAAAAAbwBAQCaAgAhvQEBAJoCACG-AUAAmwIAIb8BQACbAgAhwAFAAJsCACEBAAAA-AEAIAEAAAD4AQAgCbgBAACZAgAwuQEAAPsBABC6AQAAmQIAMLsBAQCaAgAhvAEBAJoCACG9AQEAmgIAIb4BQACbAgAhvwFAAJsCACHAAUAAmwIAIQADAAAA-wEAIAEAAPwBADACAAD4AQAgAwAAAPsBACABAAD8AQAwAgAA-AEAIAMAAAD7AQAgAQAA_AEAMAIAAPgBACAGuwEBAAAAAbwBAQAAAAG9AQEAAAABvgFAAAAAAb8BQAAAAAHAAUAAAAABARUAAIACACAGuwEBAAAAAbwBAQAAAAG9AQEAAAABvgFAAAAAAb8BQAAAAAHAAUAAAAABARUAAIICADABFQAAggIAMAa7AQEA3QIAIbwBAQDdAgAhvQEBAN0CACG-AUAA3gIAIb8BQADeAgAhwAFAAN4CACECAAAA-AEAIBUAAIUCACAGuwEBAN0CACG8AQEA3QIAIb0BAQDdAgAhvgFAAN4CACG_AUAA3gIAIcABQADeAgAhAgAAAPsBACAVAACHAgAgAgAAAPsBACAVAACHAgAgAwAAAPgBACAcAACAAgAgHQAAhQIAIAEAAAD4AQAgAQAAAPsBACADCQAA2gIAICIAANwCACAjAADbAgAgCbgBAACRAgAwuQEAAI4CABC6AQAAkQIAMLsBAQCSAgAhvAEBAJICACG9AQEAkgIAIb4BQACTAgAhvwFAAJMCACHAAUAAkwIAIQMAAAD7AQAgAQAAjQIAMCEAAI4CACADAAAA-wEAIAEAAPwBADACAAD4AQAgCbgBAACRAgAwuQEAAI4CABC6AQAAkQIAMLsBAQCSAgAhvAEBAJICACG9AQEAkgIAIb4BQACTAgAhvwFAAJMCACHAAUAAkwIAIQ4JAACVAgAgIgAAmAIAICMAAJgCACDBAQEAAAABwgEBAAAABMMBAQAAAATEAQEAAAABxQEBAAAAAcYBAQAAAAHHAQEAAAAByAEBAJcCACHJAQEAAAABygEBAAAAAcsBAQAAAAELCQAAlQIAICIAAJYCACAjAACWAgAgwQFAAAAAAcIBQAAAAATDAUAAAAAExAFAAAAAAcUBQAAAAAHGAUAAAAABxwFAAAAAAcgBQACUAgAhCwkAAJUCACAiAACWAgAgIwAAlgIAIMEBQAAAAAHCAUAAAAAEwwFAAAAABMQBQAAAAAHFAUAAAAABxgFAAAAAAccBQAAAAAHIAUAAlAIAIQjBAQIAAAABwgECAAAABMMBAgAAAATEAQIAAAABxQECAAAAAcYBAgAAAAHHAQIAAAAByAECAJUCACEIwQFAAAAAAcIBQAAAAATDAUAAAAAExAFAAAAAAcUBQAAAAAHGAUAAAAABxwFAAAAAAcgBQACWAgAhDgkAAJUCACAiAACYAgAgIwAAmAIAIMEBAQAAAAHCAQEAAAAEwwEBAAAABMQBAQAAAAHFAQEAAAABxgEBAAAAAccBAQAAAAHIAQEAlwIAIckBAQAAAAHKAQEAAAABywEBAAAAAQvBAQEAAAABwgEBAAAABMMBAQAAAATEAQEAAAABxQEBAAAAAcYBAQAAAAHHAQEAAAAByAEBAJgCACHJAQEAAAABygEBAAAAAcsBAQAAAAEJuAEAAJkCADC5AQAA-wEAELoBAACZAgAwuwEBAJoCACG8AQEAmgIAIb0BAQCaAgAhvgFAAJsCACG_AUAAmwIAIcABQACbAgAhC8EBAQAAAAHCAQEAAAAEwwEBAAAABMQBAQAAAAHFAQEAAAABxgEBAAAAAccBAQAAAAHIAQEAmAIAIckBAQAAAAHKAQEAAAABywEBAAAAAQjBAUAAAAABwgFAAAAABMMBQAAAAATEAUAAAAABxQFAAAAAAcYBQAAAAAHHAUAAAAAByAFAAJYCACEQuAEAAJwCADC5AQAA9QEAELoBAACcAgAwuwEBAJICACG_AUAAkwIAIcABQACTAgAhzAEBAJICACHNAQEAkgIAIc4BAQCSAgAhzwEBAJ0CACHQAQEAnQIAIdEBAQCdAgAh0gFAAJ4CACHTAUAAngIAIdQBAQCdAgAh1QEBAJ0CACEOCQAAoAIAICIAAKMCACAjAACjAgAgwQEBAAAAAcIBAQAAAAXDAQEAAAAFxAEBAAAAAcUBAQAAAAHGAQEAAAABxwEBAAAAAcgBAQCiAgAhyQEBAAAAAcoBAQAAAAHLAQEAAAABCwkAAKACACAiAAChAgAgIwAAoQIAIMEBQAAAAAHCAUAAAAAFwwFAAAAABcQBQAAAAAHFAUAAAAABxgFAAAAAAccBQAAAAAHIAUAAnwIAIQsJAACgAgAgIgAAoQIAICMAAKECACDBAUAAAAABwgFAAAAABcMBQAAAAAXEAUAAAAABxQFAAAAAAcYBQAAAAAHHAUAAAAAByAFAAJ8CACEIwQECAAAAAcIBAgAAAAXDAQIAAAAFxAECAAAAAcUBAgAAAAHGAQIAAAABxwECAAAAAcgBAgCgAgAhCMEBQAAAAAHCAUAAAAAFwwFAAAAABcQBQAAAAAHFAUAAAAABxgFAAAAAAccBQAAAAAHIAUAAoQIAIQ4JAACgAgAgIgAAowIAICMAAKMCACDBAQEAAAABwgEBAAAABcMBAQAAAAXEAQEAAAABxQEBAAAAAcYBAQAAAAHHAQEAAAAByAEBAKICACHJAQEAAAABygEBAAAAAcsBAQAAAAELwQEBAAAAAcIBAQAAAAXDAQEAAAAFxAEBAAAAAcUBAQAAAAHGAQEAAAABxwEBAAAAAcgBAQCjAgAhyQEBAAAAAcoBAQAAAAHLAQEAAAABC7gBAACkAgAwuQEAAN8BABC6AQAApAIAMLsBAQCSAgAhvgFAAJMCACG_AUAAkwIAIcABQACTAgAhzgEBAJICACHWAQEAkgIAIdcBAQCdAgAh2AEBAJ0CACENuAEAAKUCADC5AQAAyQEAELoBAAClAgAwuwEBAJICACG_AUAAkwIAIcABQACTAgAh2QEBAJICACHaAQEAkgIAIdsBIACmAgAh3AEBAJ0CACHeAQAApwLeASLfAQEAnQIAIeABAQCdAgAhBQkAAJUCACAiAACrAgAgIwAAqwIAIMEBIAAAAAHIASAAqgIAIQcJAACVAgAgIgAAqQIAICMAAKkCACDBAQAAAN4BAsIBAAAA3gEIwwEAAADeAQjIAQAAqALeASIHCQAAlQIAICIAAKkCACAjAACpAgAgwQEAAADeAQLCAQAAAN4BCMMBAAAA3gEIyAEAAKgC3gEiBMEBAAAA3gECwgEAAADeAQjDAQAAAN4BCMgBAACpAt4BIgUJAACVAgAgIgAAqwIAICMAAKsCACDBASAAAAAByAEgAKoCACECwQEgAAAAAcgBIACrAgAhEgQAALACACAFAACxAgAgDAAAswIAIA0AALICACAPAAC0AgAguAEAAKwCADC5AQAAtgEAELoBAACsAgAwuwEBAJoCACG_AUAAmwIAIcABQACbAgAh2QEBAJoCACHaAQEAmgIAIdsBIACtAgAh3AEBAK4CACHeAQAArwLeASLfAQEArgIAIeABAQCuAgAhAsEBIAAAAAHIASAAqwIAIQvBAQEAAAABwgEBAAAABcMBAQAAAAXEAQEAAAABxQEBAAAAAcYBAQAAAAHHAQEAAAAByAEBAKMCACHJAQEAAAABygEBAAAAAcsBAQAAAAEEwQEAAADeAQLCAQAAAN4BCMMBAAAA3gEIyAEAAKkC3gEiA-EBAAADACDiAQAAAwAg4wEAAAMAIAPhAQAABwAg4gEAAAcAIOMBAAAHACAD4QEAAAsAIOIBAAALACDjAQAACwAgA-EBAAAUACDiAQAAFAAg4wEAABQAIA4DAADNAgAgCAAAvwIAILgBAADMAgAwuQEAACAAELoBAADMAgAwuwEBAJoCACHcAQEArgIAIfUBIACtAgAh9gEBAJoCACH3AQEAmgIAIfgBAQCaAgAh-QEBAJoCACH6AQAAIAAg-wEAACAAIAm4AQAAtQIAMLkBAACwAQAQugEAALUCADC7AQEAkgIAIeQBAQCSAgAh5QEBAJICACHmAQIAtgIAIecBAQCSAgAh6AFAAJMCACENCQAAlQIAICIAAJUCACAjAACVAgAgNAAAuAIAIDUAAJUCACDBAQIAAAABwgECAAAABMMBAgAAAATEAQIAAAABxQECAAAAAcYBAgAAAAHHAQIAAAAByAECALcCACENCQAAlQIAICIAAJUCACAjAACVAgAgNAAAuAIAIDUAAJUCACDBAQIAAAABwgECAAAABMMBAgAAAATEAQIAAAABxQECAAAAAcYBAgAAAAHHAQIAAAAByAECALcCACEIwQEIAAAAAcIBCAAAAATDAQgAAAAExAEIAAAAAcUBCAAAAAHGAQgAAAABxwEIAAAAAcgBCAC4AgAhCbgBAAC5AgAwuQEAAJoBABC6AQAAuQIAMLsBAQCSAgAh5AEBAJICACHlAQEAkgIAIekBAgC2AgAh6gEQALoCACHrAQEAnQIAIQ0JAACVAgAgIgAAvAIAICMAALwCACA0AAC8AgAgNQAAvAIAIMEBEAAAAAHCARAAAAAEwwEQAAAABMQBEAAAAAHFARAAAAABxgEQAAAAAccBEAAAAAHIARAAuwIAIQ0JAACVAgAgIgAAvAIAICMAALwCACA0AAC8AgAgNQAAvAIAIMEBEAAAAAHCARAAAAAEwwEQAAAABMQBEAAAAAHFARAAAAABxgEQAAAAAccBEAAAAAHIARAAuwIAIQjBARAAAAABwgEQAAAABMMBEAAAAATEARAAAAABxQEQAAAAAcYBEAAAAAHHARAAAAAByAEQALwCACEFuAEAAL0CADC5AQAAggEAELoBAAC9AgAwuwEBAJICACHZAQEAkgIAIQYIAAC_AgAguAEAAL4CADC5AQAAbwAQugEAAL4CADC7AQEAmgIAIdkBAQCaAgAhA-EBAAAPACDiAQAADwAg4wEAAA8AIAu4AQAAwAIAMLkBAABpABC6AQAAwAIAMLsBAQCSAgAh2QEBAJICACHgAQAAwQLvASLsAQEAkgIAIe0BAQCSAgAh7wEBAJICACHwARAAugIAIfEBAQCSAgAhBwkAAJUCACAiAADDAgAgIwAAwwIAIMEBAAAA7wECwgEAAADvAQjDAQAAAO8BCMgBAADCAu8BIgcJAACVAgAgIgAAwwIAICMAAMMCACDBAQAAAO8BAsIBAAAA7wEIwwEAAADvAQjIAQAAwgLvASIEwQEAAADvAQLCAQAAAO8BCMMBAAAA7wEIyAEAAMMC7wEiCbgBAADEAgAwuQEAAFMAELoBAADEAgAwuwEBAJICACHgAQAAxQL1ASLkAQEAkgIAIegBQACTAgAh8gEBAJICACHzARAAugIAIQcJAACVAgAgIgAAxwIAICMAAMcCACDBAQAAAPUBAsIBAAAA9QEIwwEAAAD1AQjIAQAAxgL1ASIHCQAAlQIAICIAAMcCACAjAADHAgAgwQEAAAD1AQLCAQAAAPUBCMMBAAAA9QEIyAEAAMYC9QEiBMEBAAAA9QECwgEAAAD1AQjDAQAAAPUBCMgBAADHAvUBIgoNAACyAgAguAEAAMgCADC5AQAAGwAQugEAAMgCADC7AQEAmgIAIeABAADKAvUBIuQBAQCaAgAh6AFAAJsCACHyAQEAmgIAIfMBEADJAgAhCMEBEAAAAAHCARAAAAAEwwEQAAAABMQBEAAAAAHFARAAAAABxgEQAAAAAccBEAAAAAHIARAAvAIAIQTBAQAAAPUBAsIBAAAA9QEIwwEAAAD1AQjIAQAAxwL1ASIKuAEAAMsCADC5AQAAOwAQugEAAMsCADC7AQEAkgIAIdwBAQCdAgAh9QEgAKYCACH2AQEAkgIAIfcBAQCSAgAh-AEBAJICACH5AQEAkgIAIQwDAADNAgAgCAAAvwIAILgBAADMAgAwuQEAACAAELoBAADMAgAwuwEBAJoCACHcAQEArgIAIfUBIACtAgAh9gEBAJoCACH3AQEAmgIAIfgBAQCaAgAh-QEBAJoCACEUBAAAsAIAIAUAALECACAMAACzAgAgDQAAsgIAIA8AALQCACC4AQAArAIAMLkBAAC2AQAQugEAAKwCADC7AQEAmgIAIb8BQACbAgAhwAFAAJsCACHZAQEAmgIAIdoBAQCaAgAh2wEgAK0CACHcAQEArgIAId4BAACvAt4BIt8BAQCuAgAh4AEBAK4CACH6AQAAtgEAIPsBAAC2AQAgCwYAAM0CACALAADQAgAguAEAAM4CADC5AQAAFAAQugEAAM4CADC7AQEAmgIAIeQBAQCaAgAh5QEBAJoCACHmAQIAzwIAIecBAQCaAgAh6AFAAJsCACEIwQECAAAAAcIBAgAAAATDAQIAAAAExAECAAAAAcUBAgAAAAHGAQIAAAABxwECAAAAAcgBAgCVAgAhEQcAANMCACAKAADUAgAgDAAAswIAIA0AALICACC4AQAA0QIAMLkBAAAPABC6AQAA0QIAMLsBAQCaAgAh2QEBAJoCACHgAQAA0gLvASLsAQEAmgIAIe0BAQCaAgAh7wEBAJoCACHwARAAyQIAIfEBAQCaAgAh-gEAAA8AIPsBAAAPACAPBwAA0wIAIAoAANQCACAMAACzAgAgDQAAsgIAILgBAADRAgAwuQEAAA8AELoBAADRAgAwuwEBAJoCACHZAQEAmgIAIeABAADSAu8BIuwBAQCaAgAh7QEBAJoCACHvAQEAmgIAIfABEADJAgAh8QEBAJoCACEEwQEAAADvAQLCAQAAAO8BCMMBAAAA7wEIyAEAAMMC7wEiDgMAAM0CACAIAAC_AgAguAEAAMwCADC5AQAAIAAQugEAAMwCADC7AQEAmgIAIdwBAQCuAgAh9QEgAK0CACH2AQEAmgIAIfcBAQCaAgAh-AEBAJoCACH5AQEAmgIAIfoBAAAgACD7AQAAIAAgCAgAAL8CACC4AQAAvgIAMLkBAABvABC6AQAAvgIAMLsBAQCaAgAh2QEBAJoCACH6AQAAbwAg-wEAAG8AIAwGAADNAgAgCwAA0AIAIA4AANYCACC4AQAA1QIAMLkBAAALABC6AQAA1QIAMLsBAQCaAgAh5AEBAJoCACHlAQEAmgIAIekBAgDPAgAh6gEQAMkCACHrAQEArgIAIQwNAACyAgAguAEAAMgCADC5AQAAGwAQugEAAMgCADC7AQEAmgIAIeABAADKAvUBIuQBAQCaAgAh6AFAAJsCACHyAQEAmgIAIfMBEADJAgAh-gEAABsAIPsBAAAbACARAwAAzQIAILgBAADXAgAwuQEAAAcAELoBAADXAgAwuwEBAJoCACG_AUAAmwIAIcABQACbAgAhzAEBAJoCACHNAQEAmgIAIc4BAQCaAgAhzwEBAK4CACHQAQEArgIAIdEBAQCuAgAh0gFAANgCACHTAUAA2AIAIdQBAQCuAgAh1QEBAK4CACEIwQFAAAAAAcIBQAAAAAXDAUAAAAAFxAFAAAAAAcUBQAAAAAHGAUAAAAABxwFAAAAAAcgBQAChAgAhDAMAAM0CACC4AQAA2QIAMLkBAAADABC6AQAA2QIAMLsBAQCaAgAhvgFAAJsCACG_AUAAmwIAIcABQACbAgAhzgEBAJoCACHWAQEAmgIAIdcBAQCuAgAh2AEBAK4CACEAAAABggIBAAAAAQGCAkAAAAABAAAAAAGCAgEAAAABAYICQAAAAAEFHAAA2AQAIB0AANsEACD8AQAA2QQAIP0BAADaBAAggAIAALMBACADHAAA2AQAIPwBAADZBAAggAIAALMBACAAAAAFHAAA0wQAIB0AANYEACD8AQAA1AQAIP0BAADVBAAggAIAALMBACADHAAA0wQAIPwBAADUBAAggAIAALMBACAAAAABggIgAAAAAQGCAgAAAN4BAgscAADSAwAwHQAA1wMAMPwBAADTAwAw_QEAANQDADD-AQAA1gMAMP8BAADWAwAwgAIAANYDADCBAgAA1QMAIIICAADWAwAwgwIAANgDADCEAgAA2QMAMAscAADGAwAwHQAAywMAMPwBAADHAwAw_QEAAMgDADD-AQAAygMAMP8BAADKAwAwgAIAAMoDADCBAgAAyQMAIIICAADKAwAwgwIAAMwDADCEAgAAzQMAMAscAAC7AwAwHQAAvwMAMPwBAAC8AwAw_QEAAL0DADD-AQAAkAMAMP8BAACQAwAwgAIAAJADADCBAgAAvgMAIIICAACQAwAwgwIAAMADADCEAgAAkwMAMAscAACwAwAwHQAAtAMAMPwBAACxAwAw_QEAALIDADD-AQAAoQMAMP8BAAChAwAwgAIAAKEDADCBAgAAswMAIIICAAChAwAwgwIAALUDADCEAgAApAMAMAccAAD2AgAgHQAA-QIAIPwBAAD3AgAg_QEAAPgCACD-AQAAIAAg_wEAACAAIIACAAABACAHCAAArwMAILsBAQAAAAHcAQEAAAAB9QEgAAAAAfcBAQAAAAH4AQEAAAAB-QEBAAAAAQIAAAABACAcAAD2AgAgAwAAACAAIBwAAPYCACAdAAD6AgAgCQAAACAAIAgAAPsCACAVAAD6AgAguwEBAN0CACHcAQEA4wIAIfUBIADvAgAh9wEBAN0CACH4AQEA3QIAIfkBAQDdAgAhBwgAAPsCACC7AQEA3QIAIdwBAQDjAgAh9QEgAO8CACH3AQEA3QIAIfgBAQDdAgAh-QEBAN0CACELHAAA_AIAMB0AAIEDADD8AQAA_QIAMP0BAAD-AgAw_gEAAIADADD_AQAAgAMAMIACAACAAwAwgQIAAP8CACCCAgAAgAMAMIMCAACCAwAwhAIAAIMDADAKCgAArAMAIAwAAK0DACANAACuAwAguwEBAAAAAdkBAQAAAAHgAQAAAO8BAu0BAQAAAAHvAQEAAAAB8AEQAAAAAfEBAQAAAAECAAAAEQAgHAAAqwMAIAMAAAARACAcAACrAwAgHQAAiAMAIAEVAADSBAAwDwcAANMCACAKAADUAgAgDAAAswIAIA0AALICACC4AQAA0QIAMLkBAAAPABC6AQAA0QIAMLsBAQAAAAHZAQEAmgIAIeABAADSAu8BIuwBAQCaAgAh7QEBAJoCACHvAQEAmgIAIfABEADJAgAh8QEBAJoCACECAAAAEQAgFQAAiAMAIAIAAACEAwAgFQAAhQMAIAu4AQAAgwMAMLkBAACEAwAQugEAAIMDADC7AQEAmgIAIdkBAQCaAgAh4AEAANIC7wEi7AEBAJoCACHtAQEAmgIAIe8BAQCaAgAh8AEQAMkCACHxAQEAmgIAIQu4AQAAgwMAMLkBAACEAwAQugEAAIMDADC7AQEAmgIAIdkBAQCaAgAh4AEAANIC7wEi7AEBAJoCACHtAQEAmgIAIe8BAQCaAgAh8AEQAMkCACHxAQEAmgIAIQe7AQEA3QIAIdkBAQDdAgAh4AEAAIYD7wEi7QEBAN0CACHvAQEA3QIAIfABEACHAwAh8QEBAN0CACEBggIAAADvAQIFggIQAAAAAYUCEAAAAAGGAhAAAAABhwIQAAAAAYgCEAAAAAEKCgAAiQMAIAwAAIoDACANAACLAwAguwEBAN0CACHZAQEA3QIAIeABAACGA-8BIu0BAQDdAgAh7wEBAN0CACHwARAAhwMAIfEBAQDdAgAhBRwAALwEACAdAADQBAAg_AEAAL0EACD9AQAAzwQAIIACAABsACALHAAAnQMAMB0AAKIDADD8AQAAngMAMP0BAACfAwAw_gEAAKEDADD_AQAAoQMAMIACAAChAwAwgQIAAKADACCCAgAAoQMAMIMCAACjAwAwhAIAAKQDADALHAAAjAMAMB0AAJEDADD8AQAAjQMAMP0BAACOAwAw_gEAAJADADD_AQAAkAMAMIACAACQAwAwgQIAAI8DACCCAgAAkAMAMIMCAACSAwAwhAIAAJMDADAHBgAAmwMAIA4AAJwDACC7AQEAAAAB5AEBAAAAAekBAgAAAAHqARAAAAAB6wEBAAAAAQIAAAANACAcAACaAwAgAwAAAA0AIBwAAJoDACAdAACXAwAgARUAAM4EADAMBgAAzQIAIAsAANACACAOAADWAgAguAEAANUCADC5AQAACwAQugEAANUCADC7AQEAAAAB5AEBAJoCACHlAQEAmgIAIekBAgDPAgAh6gEQAMkCACHrAQEArgIAIQIAAAANACAVAACXAwAgAgAAAJQDACAVAACVAwAgCbgBAACTAwAwuQEAAJQDABC6AQAAkwMAMLsBAQCaAgAh5AEBAJoCACHlAQEAmgIAIekBAgDPAgAh6gEQAMkCACHrAQEArgIAIQm4AQAAkwMAMLkBAACUAwAQugEAAJMDADC7AQEAmgIAIeQBAQCaAgAh5QEBAJoCACHpAQIAzwIAIeoBEADJAgAh6wEBAK4CACEFuwEBAN0CACHkAQEA3QIAIekBAgCWAwAh6gEQAIcDACHrAQEA4wIAIQWCAgIAAAABhQICAAAAAYYCAgAAAAGHAgIAAAABiAICAAAAAQcGAACYAwAgDgAAmQMAILsBAQDdAgAh5AEBAN0CACHpAQIAlgMAIeoBEACHAwAh6wEBAOMCACEFHAAAxgQAIB0AAMwEACD8AQAAxwQAIP0BAADLBAAggAIAALMBACAHHAAAxAQAIB0AAMkEACD8AQAAxQQAIP0BAADIBAAg_gEAABsAIP8BAAAbACCAAgAAPgAgBwYAAJsDACAOAACcAwAguwEBAAAAAeQBAQAAAAHpAQIAAAAB6gEQAAAAAesBAQAAAAEDHAAAxgQAIPwBAADHBAAggAIAALMBACADHAAAxAQAIPwBAADFBAAggAIAAD4AIAYGAACqAwAguwEBAAAAAeQBAQAAAAHmAQIAAAAB5wEBAAAAAegBQAAAAAECAAAAFgAgHAAAqQMAIAMAAAAWACAcAACpAwAgHQAApwMAIAEVAADDBAAwCwYAAM0CACALAADQAgAguAEAAM4CADC5AQAAFAAQugEAAM4CADC7AQEAAAAB5AEBAJoCACHlAQEAmgIAIeYBAgDPAgAh5wEBAJoCACHoAUAAmwIAIQIAAAAWACAVAACnAwAgAgAAAKUDACAVAACmAwAgCbgBAACkAwAwuQEAAKUDABC6AQAApAMAMLsBAQCaAgAh5AEBAJoCACHlAQEAmgIAIeYBAgDPAgAh5wEBAJoCACHoAUAAmwIAIQm4AQAApAMAMLkBAAClAwAQugEAAKQDADC7AQEAmgIAIeQBAQCaAgAh5QEBAJoCACHmAQIAzwIAIecBAQCaAgAh6AFAAJsCACEFuwEBAN0CACHkAQEA3QIAIeYBAgCWAwAh5wEBAN0CACHoAUAA3gIAIQYGAACoAwAguwEBAN0CACHkAQEA3QIAIeYBAgCWAwAh5wEBAN0CACHoAUAA3gIAIQUcAAC-BAAgHQAAwQQAIPwBAAC_BAAg_QEAAMAEACCAAgAAswEAIAYGAACqAwAguwEBAAAAAeQBAQAAAAHmAQIAAAAB5wEBAAAAAegBQAAAAAEDHAAAvgQAIPwBAAC_BAAggAIAALMBACAKCgAArAMAIAwAAK0DACANAACuAwAguwEBAAAAAdkBAQAAAAHgAQAAAO8BAu0BAQAAAAHvAQEAAAAB8AEQAAAAAfEBAQAAAAEDHAAAvAQAIPwBAAC9BAAggAIAAGwAIAQcAACdAwAw_AEAAJ4DADCAAgAAoQMAMIECAACgAwAgBBwAAIwDADD8AQAAjQMAMIACAACQAwAwgQIAAI8DACAEHAAA_AIAMPwBAAD9AgAwgAIAAIADADCBAgAA_wIAIAYLAAC6AwAguwEBAAAAAeUBAQAAAAHmAQIAAAAB5wEBAAAAAegBQAAAAAECAAAAFgAgHAAAuQMAIAMAAAAWACAcAAC5AwAgHQAAtwMAIAEVAAC7BAAwAgAAABYAIBUAALcDACACAAAApQMAIBUAALYDACAFuwEBAN0CACHlAQEA3QIAIeYBAgCWAwAh5wEBAN0CACHoAUAA3gIAIQYLAAC4AwAguwEBAN0CACHlAQEA3QIAIeYBAgCWAwAh5wEBAN0CACHoAUAA3gIAIQUcAAC2BAAgHQAAuQQAIPwBAAC3BAAg_QEAALgEACCAAgAAEQAgBgsAALoDACC7AQEAAAAB5QEBAAAAAeYBAgAAAAHnAQEAAAAB6AFAAAAAAQMcAAC2BAAg_AEAALcEACCAAgAAEQAgBwsAAMUDACAOAACcAwAguwEBAAAAAeUBAQAAAAHpAQIAAAAB6gEQAAAAAesBAQAAAAECAAAADQAgHAAAxAMAIAMAAAANACAcAADEAwAgHQAAwgMAIAEVAAC1BAAwAgAAAA0AIBUAAMIDACACAAAAlAMAIBUAAMEDACAFuwEBAN0CACHlAQEA3QIAIekBAgCWAwAh6gEQAIcDACHrAQEA4wIAIQcLAADDAwAgDgAAmQMAILsBAQDdAgAh5QEBAN0CACHpAQIAlgMAIeoBEACHAwAh6wEBAOMCACEFHAAAsAQAIB0AALMEACD8AQAAsQQAIP0BAACyBAAggAIAABEAIAcLAADFAwAgDgAAnAMAILsBAQAAAAHlAQEAAAAB6QECAAAAAeoBEAAAAAHrAQEAAAABAxwAALAEACD8AQAAsQQAIIACAAARACAMuwEBAAAAAb8BQAAAAAHAAUAAAAABzAEBAAAAAc0BAQAAAAHPAQEAAAAB0AEBAAAAAdEBAQAAAAHSAUAAAAAB0wFAAAAAAdQBAQAAAAHVAQEAAAABAgAAAAkAIBwAANEDACADAAAACQAgHAAA0QMAIB0AANADACABFQAArwQAMBEDAADNAgAguAEAANcCADC5AQAABwAQugEAANcCADC7AQEAAAABvwFAAJsCACHAAUAAmwIAIcwBAQCaAgAhzQEBAJoCACHOAQEAmgIAIc8BAQCuAgAh0AEBAK4CACHRAQEArgIAIdIBQADYAgAh0wFAANgCACHUAQEArgIAIdUBAQCuAgAhAgAAAAkAIBUAANADACACAAAAzgMAIBUAAM8DACAQuAEAAM0DADC5AQAAzgMAELoBAADNAwAwuwEBAJoCACG_AUAAmwIAIcABQACbAgAhzAEBAJoCACHNAQEAmgIAIc4BAQCaAgAhzwEBAK4CACHQAQEArgIAIdEBAQCuAgAh0gFAANgCACHTAUAA2AIAIdQBAQCuAgAh1QEBAK4CACEQuAEAAM0DADC5AQAAzgMAELoBAADNAwAwuwEBAJoCACG_AUAAmwIAIcABQACbAgAhzAEBAJoCACHNAQEAmgIAIc4BAQCaAgAhzwEBAK4CACHQAQEArgIAIdEBAQCuAgAh0gFAANgCACHTAUAA2AIAIdQBAQCuAgAh1QEBAK4CACEMuwEBAN0CACG_AUAA3gIAIcABQADeAgAhzAEBAN0CACHNAQEA3QIAIc8BAQDjAgAh0AEBAOMCACHRAQEA4wIAIdIBQADkAgAh0wFAAOQCACHUAQEA4wIAIdUBAQDjAgAhDLsBAQDdAgAhvwFAAN4CACHAAUAA3gIAIcwBAQDdAgAhzQEBAN0CACHPAQEA4wIAIdABAQDjAgAh0QEBAOMCACHSAUAA5AIAIdMBQADkAgAh1AEBAOMCACHVAQEA4wIAIQy7AQEAAAABvwFAAAAAAcABQAAAAAHMAQEAAAABzQEBAAAAAc8BAQAAAAHQAQEAAAAB0QEBAAAAAdIBQAAAAAHTAUAAAAAB1AEBAAAAAdUBAQAAAAEHuwEBAAAAAb4BQAAAAAG_AUAAAAABwAFAAAAAAdYBAQAAAAHXAQEAAAAB2AEBAAAAAQIAAAAFACAcAADdAwAgAwAAAAUAIBwAAN0DACAdAADcAwAgARUAAK4EADAMAwAAzQIAILgBAADZAgAwuQEAAAMAELoBAADZAgAwuwEBAAAAAb4BQACbAgAhvwFAAJsCACHAAUAAmwIAIc4BAQCaAgAh1gEBAAAAAdcBAQCuAgAh2AEBAK4CACECAAAABQAgFQAA3AMAIAIAAADaAwAgFQAA2wMAIAu4AQAA2QMAMLkBAADaAwAQugEAANkDADC7AQEAmgIAIb4BQACbAgAhvwFAAJsCACHAAUAAmwIAIc4BAQCaAgAh1gEBAJoCACHXAQEArgIAIdgBAQCuAgAhC7gBAADZAwAwuQEAANoDABC6AQAA2QMAMLsBAQCaAgAhvgFAAJsCACG_AUAAmwIAIcABQACbAgAhzgEBAJoCACHWAQEAmgIAIdcBAQCuAgAh2AEBAK4CACEHuwEBAN0CACG-AUAA3gIAIb8BQADeAgAhwAFAAN4CACHWAQEA3QIAIdcBAQDjAgAh2AEBAOMCACEHuwEBAN0CACG-AUAA3gIAIb8BQADeAgAhwAFAAN4CACHWAQEA3QIAIdcBAQDjAgAh2AEBAOMCACEHuwEBAAAAAb4BQAAAAAG_AUAAAAABwAFAAAAAAdYBAQAAAAHXAQEAAAAB2AEBAAAAAQQcAADSAwAw_AEAANMDADCAAgAA1gMAMIECAADVAwAgBBwAAMYDADD8AQAAxwMAMIACAADKAwAwgQIAAMkDACAEHAAAuwMAMPwBAAC8AwAwgAIAAJADADCBAgAAvgMAIAQcAACwAwAw_AEAALEDADCAAgAAoQMAMIECAACzAwAgAxwAAPYCACD8AQAA9wIAIIACAAABACAAAAAAAwMAAJ4EACAIAACCBAAg3AEAAN8CACAAAAAAAAAAAAAAAAAACxwAAPYDADAdAAD6AwAw_AEAAPcDADD9AQAA-AMAMP4BAACAAwAw_wEAAIADADCAAgAAgAMAMIECAAD5AwAgggIAAIADADCDAgAA-wMAMIQCAACDAwAwCgcAAIAEACAMAACtAwAgDQAArgMAILsBAQAAAAHZAQEAAAAB4AEAAADvAQLsAQEAAAAB7wEBAAAAAfABEAAAAAHxAQEAAAABAgAAABEAIBwAAP8DACADAAAAEQAgHAAA_wMAIB0AAP0DACABFQAArQQAMAIAAAARACAVAAD9AwAgAgAAAIQDACAVAAD8AwAgB7sBAQDdAgAh2QEBAN0CACHgAQAAhgPvASLsAQEA3QIAIe8BAQDdAgAh8AEQAIcDACHxAQEA3QIAIQoHAAD-AwAgDAAAigMAIA0AAIsDACC7AQEA3QIAIdkBAQDdAgAh4AEAAIYD7wEi7AEBAN0CACHvAQEA3QIAIfABEACHAwAh8QEBAN0CACEFHAAAqAQAIB0AAKsEACD8AQAAqQQAIP0BAACqBAAggAIAAAEAIAoHAACABAAgDAAArQMAIA0AAK4DACC7AQEAAAAB2QEBAAAAAeABAAAA7wEC7AEBAAAAAe8BAQAAAAHwARAAAAAB8QEBAAAAAQMcAACoBAAg_AEAAKkEACCAAgAAAQAgBBwAAPYDADD8AQAA9wMAMIACAACAAwAwgQIAAPkDACAAAAAAAAAAAAAAAAGCAgAAAPUBAgscAACPBAAwHQAAkwQAMPwBAACQBAAw_QEAAJEEADD-AQAAkAMAMP8BAACQAwAwgAIAAJADADCBAgAAkgQAIIICAACQAwAwgwIAAJQEADCEAgAAkwMAMAcGAACbAwAgCwAAxQMAILsBAQAAAAHkAQEAAAAB5QEBAAAAAekBAgAAAAHqARAAAAABAgAAAA0AIBwAAJcEACADAAAADQAgHAAAlwQAIB0AAJYEACABFQAApwQAMAIAAAANACAVAACWBAAgAgAAAJQDACAVAACVBAAgBbsBAQDdAgAh5AEBAN0CACHlAQEA3QIAIekBAgCWAwAh6gEQAIcDACEHBgAAmAMAIAsAAMMDACC7AQEA3QIAIeQBAQDdAgAh5QEBAN0CACHpAQIAlgMAIeoBEACHAwAhBwYAAJsDACALAADFAwAguwEBAAAAAeQBAQAAAAHlAQEAAAAB6QECAAAAAeoBEAAAAAEEHAAAjwQAMPwBAACQBAAwgAIAAJADADCBAgAAkgQAIAAAAAUcAACiBAAgHQAApQQAIPwBAACjBAAg_QEAAKQEACCAAgAAswEAIAMcAACiBAAg_AEAAKMEACCAAgAAswEAIAgEAADjAwAgBQAA5AMAIAwAAOYDACANAADlAwAgDwAA5wMAINwBAADfAgAg3wEAAN8CACDgAQAA3wIAIAQHAADnAwAgCgAAoAQAIAwAAOYDACANAADlAwAgAQgAAIIEACABDQAA5QMAIA4EAADeAwAgBQAA3wMAIAwAAOEDACANAADgAwAguwEBAAAAAb8BQAAAAAHAAUAAAAAB2QEBAAAAAdoBAQAAAAHbASAAAAAB3AEBAAAAAd4BAAAA3gEC3wEBAAAAAeABAQAAAAECAAAAswEAIBwAAKIEACADAAAAtgEAIBwAAKIEACAdAACmBAAgEAAAALYBACAEAADxAgAgBQAA8gIAIAwAAPQCACANAADzAgAgFQAApgQAILsBAQDdAgAhvwFAAN4CACHAAUAA3gIAIdkBAQDdAgAh2gEBAN0CACHbASAA7wIAIdwBAQDjAgAh3gEAAPAC3gEi3wEBAOMCACHgAQEA4wIAIQ4EAADxAgAgBQAA8gIAIAwAAPQCACANAADzAgAguwEBAN0CACG_AUAA3gIAIcABQADeAgAh2QEBAN0CACHaAQEA3QIAIdsBIADvAgAh3AEBAOMCACHeAQAA8ALeASLfAQEA4wIAIeABAQDjAgAhBbsBAQAAAAHkAQEAAAAB5QEBAAAAAekBAgAAAAHqARAAAAABCAMAAJ0EACC7AQEAAAAB3AEBAAAAAfUBIAAAAAH2AQEAAAAB9wEBAAAAAfgBAQAAAAH5AQEAAAABAgAAAAEAIBwAAKgEACADAAAAIAAgHAAAqAQAIB0AAKwEACAKAAAAIAAgAwAAnAQAIBUAAKwEACC7AQEA3QIAIdwBAQDjAgAh9QEgAO8CACH2AQEA3QIAIfcBAQDdAgAh-AEBAN0CACH5AQEA3QIAIQgDAACcBAAguwEBAN0CACHcAQEA4wIAIfUBIADvAgAh9gEBAN0CACH3AQEA3QIAIfgBAQDdAgAh-QEBAN0CACEHuwEBAAAAAdkBAQAAAAHgAQAAAO8BAuwBAQAAAAHvAQEAAAAB8AEQAAAAAfEBAQAAAAEHuwEBAAAAAb4BQAAAAAG_AUAAAAABwAFAAAAAAdYBAQAAAAHXAQEAAAAB2AEBAAAAAQy7AQEAAAABvwFAAAAAAcABQAAAAAHMAQEAAAABzQEBAAAAAc8BAQAAAAHQAQEAAAAB0QEBAAAAAdIBQAAAAAHTAUAAAAAB1AEBAAAAAdUBAQAAAAELBwAAgAQAIAoAAKwDACAMAACtAwAguwEBAAAAAdkBAQAAAAHgAQAAAO8BAuwBAQAAAAHtAQEAAAAB7wEBAAAAAfABEAAAAAHxAQEAAAABAgAAABEAIBwAALAEACADAAAADwAgHAAAsAQAIB0AALQEACANAAAADwAgBwAA_gMAIAoAAIkDACAMAACKAwAgFQAAtAQAILsBAQDdAgAh2QEBAN0CACHgAQAAhgPvASLsAQEA3QIAIe0BAQDdAgAh7wEBAN0CACHwARAAhwMAIfEBAQDdAgAhCwcAAP4DACAKAACJAwAgDAAAigMAILsBAQDdAgAh2QEBAN0CACHgAQAAhgPvASLsAQEA3QIAIe0BAQDdAgAh7wEBAN0CACHwARAAhwMAIfEBAQDdAgAhBbsBAQAAAAHlAQEAAAAB6QECAAAAAeoBEAAAAAHrAQEAAAABCwcAAIAEACAKAACsAwAgDQAArgMAILsBAQAAAAHZAQEAAAAB4AEAAADvAQLsAQEAAAAB7QEBAAAAAe8BAQAAAAHwARAAAAAB8QEBAAAAAQIAAAARACAcAAC2BAAgAwAAAA8AIBwAALYEACAdAAC6BAAgDQAAAA8AIAcAAP4DACAKAACJAwAgDQAAiwMAIBUAALoEACC7AQEA3QIAIdkBAQDdAgAh4AEAAIYD7wEi7AEBAN0CACHtAQEA3QIAIe8BAQDdAgAh8AEQAIcDACHxAQEA3QIAIQsHAAD-AwAgCgAAiQMAIA0AAIsDACC7AQEA3QIAIdkBAQDdAgAh4AEAAIYD7wEi7AEBAN0CACHtAQEA3QIAIe8BAQDdAgAh8AEQAIcDACHxAQEA3QIAIQW7AQEAAAAB5QEBAAAAAeYBAgAAAAHnAQEAAAAB6AFAAAAAAQK7AQEAAAAB2QEBAAAAAQIAAABsACAcAAC8BAAgDgQAAN4DACAFAADfAwAgDQAA4AMAIA8AAOIDACC7AQEAAAABvwFAAAAAAcABQAAAAAHZAQEAAAAB2gEBAAAAAdsBIAAAAAHcAQEAAAAB3gEAAADeAQLfAQEAAAAB4AEBAAAAAQIAAACzAQAgHAAAvgQAIAMAAAC2AQAgHAAAvgQAIB0AAMIEACAQAAAAtgEAIAQAAPECACAFAADyAgAgDQAA8wIAIA8AAPUCACAVAADCBAAguwEBAN0CACG_AUAA3gIAIcABQADeAgAh2QEBAN0CACHaAQEA3QIAIdsBIADvAgAh3AEBAOMCACHeAQAA8ALeASLfAQEA4wIAIeABAQDjAgAhDgQAAPECACAFAADyAgAgDQAA8wIAIA8AAPUCACC7AQEA3QIAIb8BQADeAgAhwAFAAN4CACHZAQEA3QIAIdoBAQDdAgAh2wEgAO8CACHcAQEA4wIAId4BAADwAt4BIt8BAQDjAgAh4AEBAOMCACEFuwEBAAAAAeQBAQAAAAHmAQIAAAAB5wEBAAAAAegBQAAAAAEGuwEBAAAAAeABAAAA9QEC5AEBAAAAAegBQAAAAAHyAQEAAAAB8wEQAAAAAQIAAAA-ACAcAADEBAAgDgQAAN4DACAFAADfAwAgDAAA4QMAIA8AAOIDACC7AQEAAAABvwFAAAAAAcABQAAAAAHZAQEAAAAB2gEBAAAAAdsBIAAAAAHcAQEAAAAB3gEAAADeAQLfAQEAAAAB4AEBAAAAAQIAAACzAQAgHAAAxgQAIAMAAAAbACAcAADEBAAgHQAAygQAIAgAAAAbACAVAADKBAAguwEBAN0CACHgAQAAjQT1ASLkAQEA3QIAIegBQADeAgAh8gEBAN0CACHzARAAhwMAIQa7AQEA3QIAIeABAACNBPUBIuQBAQDdAgAh6AFAAN4CACHyAQEA3QIAIfMBEACHAwAhAwAAALYBACAcAADGBAAgHQAAzQQAIBAAAAC2AQAgBAAA8QIAIAUAAPICACAMAAD0AgAgDwAA9QIAIBUAAM0EACC7AQEA3QIAIb8BQADeAgAhwAFAAN4CACHZAQEA3QIAIdoBAQDdAgAh2wEgAO8CACHcAQEA4wIAId4BAADwAt4BIt8BAQDjAgAh4AEBAOMCACEOBAAA8QIAIAUAAPICACAMAAD0AgAgDwAA9QIAILsBAQDdAgAhvwFAAN4CACHAAUAA3gIAIdkBAQDdAgAh2gEBAN0CACHbASAA7wIAIdwBAQDjAgAh3gEAAPAC3gEi3wEBAOMCACHgAQEA4wIAIQW7AQEAAAAB5AEBAAAAAekBAgAAAAHqARAAAAAB6wEBAAAAAQMAAABvACAcAAC8BAAgHQAA0QQAIAQAAABvACAVAADRBAAguwEBAN0CACHZAQEA3QIAIQK7AQEA3QIAIdkBAQDdAgAhB7sBAQAAAAHZAQEAAAAB4AEAAADvAQLtAQEAAAAB7wEBAAAAAfABEAAAAAHxAQEAAAABDgUAAN8DACAMAADhAwAgDQAA4AMAIA8AAOIDACC7AQEAAAABvwFAAAAAAcABQAAAAAHZAQEAAAAB2gEBAAAAAdsBIAAAAAHcAQEAAAAB3gEAAADeAQLfAQEAAAAB4AEBAAAAAQIAAACzAQAgHAAA0wQAIAMAAAC2AQAgHAAA0wQAIB0AANcEACAQAAAAtgEAIAUAAPICACAMAAD0AgAgDQAA8wIAIA8AAPUCACAVAADXBAAguwEBAN0CACG_AUAA3gIAIcABQADeAgAh2QEBAN0CACHaAQEA3QIAIdsBIADvAgAh3AEBAOMCACHeAQAA8ALeASLfAQEA4wIAIeABAQDjAgAhDgUAAPICACAMAAD0AgAgDQAA8wIAIA8AAPUCACC7AQEA3QIAIb8BQADeAgAhwAFAAN4CACHZAQEA3QIAIdoBAQDdAgAh2wEgAO8CACHcAQEA4wIAId4BAADwAt4BIt8BAQDjAgAh4AEBAOMCACEOBAAA3gMAIAwAAOEDACANAADgAwAgDwAA4gMAILsBAQAAAAG_AUAAAAABwAFAAAAAAdkBAQAAAAHaAQEAAAAB2wEgAAAAAdwBAQAAAAHeAQAAAN4BAt8BAQAAAAHgAQEAAAABAgAAALMBACAcAADYBAAgAwAAALYBACAcAADYBAAgHQAA3AQAIBAAAAC2AQAgBAAA8QIAIAwAAPQCACANAADzAgAgDwAA9QIAIBUAANwEACC7AQEA3QIAIb8BQADeAgAhwAFAAN4CACHZAQEA3QIAIdoBAQDdAgAh2wEgAO8CACHcAQEA4wIAId4BAADwAt4BIt8BAQDjAgAh4AEBAOMCACEOBAAA8QIAIAwAAPQCACANAADzAgAgDwAA9QIAILsBAQDdAgAhvwFAAN4CACHAAUAA3gIAIdkBAQDdAgAh2gEBAN0CACHbASAA7wIAIdwBAQDjAgAh3gEAAPAC3gEi3wEBAOMCACHgAQEA4wIAIQMDAAIIJgYJAA4GBAYDBQoECQANDB8JDQ4FDyEBAQMAAgEDAAIDBgACCwAGDhwLBQcAAQkACgoABwwXCQ0YBQIIEgYJAAgBCBMAAgYAAgsABgIMGQANGgACCQAMDR0FAQ0eAAQEIgAFIwAMJQANJAABCCcAAAEDAAIBAwACAwkAEyIAFCMAFQAAAAMJABMiABQjABUAAAUJABoiAB0jAB40ABs1ABwAAAAAAAUJABoiAB0jAB40ABs1ABwCBwABCgAHAgcAAQoABwUJACMiACYjACc0ACQ1ACUAAAAAAAUJACMiACYjACc0ACQ1ACUAAAMJACwiAC0jAC4AAAADCQAsIgAtIwAuAwYAAgsABg6PAQsDBgACCwAGDpUBCwUJADMiADYjADc0ADQ1ADUAAAAAAAUJADMiADYjADc0ADQ1ADUCBgACCwAGAgYAAgsABgUJADwiAD8jAEA0AD01AD4AAAAAAAUJADwiAD8jAEA0AD01AD4AAAMJAEUiAEYjAEcAAAADCQBFIgBGIwBHAQMAAgEDAAIDCQBMIgBNIwBOAAAAAwkATCIATSMATgEDAAIBAwACAwkAUyIAVCMAVQAAAAMJAFMiAFQjAFUAAAADCQBbIgBcIwBdAAAAAwkAWyIAXCMAXRACAREoARIqARMrARQsARYuARcwDxgxEBkzARo1Dxs2ER43AR84ASA5DyQ8EiU9FiY_CydACyhCCylDCypECytGCyxIDy1JFy5LCy9NDzBOGDFPCzJQCzNRDzZUGTdVHzhWBjlXBjpYBjtZBjxaBj1cBj5eDz9fIEBhBkFjD0JkIUNlBkRmBkVnD0ZqIkdrKEhtB0luB0pxB0tyB0xzB011B053D094KVB6B1F8D1J9KlN-B1R_B1WAAQ9WgwErV4QBL1iFAQVZhgEFWocBBVuIAQVciQEFXYsBBV6NAQ9fjgEwYJEBBWGTAQ9ilAExY5YBBWSXAQVlmAEPZpsBMmecAThonQEJaZ4BCWqfAQlroAEJbKEBCW2jAQlupQEPb6YBOXCoAQlxqgEPcqsBOnOsAQl0rQEJda4BD3axATt3sgFBeLQBAnm1AQJ6uAECe7kBAny6AQJ9vAECfr4BD3-_AUKAAcEBAoEBwwEPggHEAUODAcUBAoQBxgEChQHHAQ-GAcoBRIcBywFIiAHMAQOJAc0BA4oBzgEDiwHPAQOMAdABA40B0gEDjgHUAQ-PAdUBSZAB1wEDkQHZAQ-SAdoBSpMB2wEDlAHcAQOVAd0BD5YB4AFLlwHhAU-YAeIBBJkB4wEEmgHkAQSbAeUBBJwB5gEEnQHoAQSeAeoBD58B6wFQoAHtAQShAe8BD6IB8AFRowHxAQSkAfIBBKUB8wEPpgH2AVKnAfcBVqgB-QFXqQH6AVeqAf0BV6sB_gFXrAH_AVetAYECV64BgwIPrwGEAliwAYYCV7EBiAIPsgGJAlmzAYoCV7QBiwJXtQGMAg-2AY8CWrcBkAJe"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer } = await import("buffer");
  const wasmArray = Buffer.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// generated/prisma/internal/prismaNamespace.ts
import * as runtime2 from "@prisma/client/runtime/client";
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var defineExtension = runtime2.Extensions.defineExtension;

// generated/prisma/enums.ts
var OrderStatus = {
  PLACED: "PLACED",
  PREPARING: "PREPARING",
  READY: "READY",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED"
};
var UserRole = {
  USER: "USER",
  ADMIN: "ADMIN",
  PROVIDER: "PROVIDER"
};

// generated/prisma/client.ts
globalThis["__dirname"] = path.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// src/lib/prisma.ts
var connectionString = `${process.env.DATABASE_URL}`;
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// src/modules/provider/provider.service.ts
var createProviderProfile = async (data, userId) => {
  const result = await prisma.provider_Profile.create({
    data: {
      ...data,
      user_id: userId,
      // <-- only use user_id, DO NOT include `user` object
      image: data.image || null
    }
  });
  return result;
};
var getProviderProfile = async () => {
  const Profile = await prisma.provider_Profile.findFirst();
  return Profile;
};
var getAllSystemStatsForAdmin = async () => {
  const providers = await prisma.provider_Profile.findMany({
    include: {
      _count: {
        select: { meals: true }
      },
      meals: {
        include: {
          orderItems: {
            include: {
              orders: true
            }
          },
          category: true
          // ক্যাটাগরি নাম দেখানোর জন্য
        }
      }
    }
  });
  return providers.map((p) => {
    let totalRevenue = 0;
    let activeOrdersCount = 0;
    let totalOrdersCount = 0;
    p.meals.forEach((meal) => {
      meal.orderItems.forEach((item) => {
        if (item.orders) {
          totalOrdersCount++;
          if (["PLACED", "PREPARING", "READY"].includes(item.orders.status)) {
            activeOrdersCount++;
          }
          if (item.orders.status === "DELIVERED") {
            totalRevenue += Number(item.price_at_order) * item.quantity;
          }
        }
      });
    });
    return {
      id: p.id,
      restaurantName: p.restaurant_name,
      address: p.address,
      totalMeals: p._count.meals,
      totalOrders: totalOrdersCount,
      activeOrders: activeOrdersCount,
      totalRevenue,
      // প্রতিটি খাবারের ডিটেইলস এবং স্ট্যাটাস এখানে আসবে
      meals: p.meals.map((m) => ({
        id: m.id,
        name: m.name,
        price: Number(m.price),
        status: m.status,
        // AVAILABLE or UNAVAILABLE
        category: m.category.name,
        image: m.image_url
      }))
    };
  });
};
var updateProviderStatus = async (id, is_active) => {
  return await prisma.provider_Profile.update({
    where: { id },
    data: { is_active }
  });
};
var getAllProviders = async () => {
  try {
    const providers = await prisma.provider_Profile.findMany({
      include: {
        _count: { select: { meals: true } },
        meals: {
          include: {
            orderItems: {
              include: { orders: true }
            }
          }
        }
      }
    });
    return providers.map((p) => {
      let totalRevenue = 0;
      let activeOrdersCount = 0;
      let totalOrdersCount = 0;
      p.meals.forEach((meal) => {
        meal.orderItems.forEach((item) => {
          if (item.orders) {
            totalOrdersCount++;
            if (["PLACED", "PREPARING", "READY"].includes(item.orders.status)) {
              activeOrdersCount++;
            }
            if (item.orders.status === "DELIVERED") {
              totalRevenue += Number(item.price_at_order) * item.quantity;
            }
          }
        });
      });
      return {
        id: p.id,
        restaurantName: p.restaurant_name,
        address: p.address,
        contactNumber: p.contact_number,
        image: p.image || "/default-restaurant.png",
        // default image
        totalMeals: p._count.meals,
        totalOrders: totalOrdersCount,
        activeOrders: activeOrdersCount,
        totalRevenue
      };
    });
  } catch (error) {
    throw new Error("Error fetching providers");
  }
};
var getSingleProviderStats = async (providerId) => {
  console.log("searching for provider  id :", providerId);
  const profile = await prisma.provider_Profile.findUnique({
    where: { id: providerId }
  });
  const meals = await prisma.meals.findMany({
    where: { provider_id: providerId },
    include: {
      category: true
      // যাতে খাবারের ক্যাটাগরির নাম দেখা যায়
    }
  });
  return {
    ...profile,
    meals: meals.map((meal) => ({
      ...meal,
      category: meal.category.name
      // ক্যাটাগরি অবজেক্ট থেকে শুধু নামটা নিয়ে আসা
    }))
  };
};
var providerService = {
  createProviderProfile,
  getProviderProfile,
  getAllSystemStatsForAdmin,
  updateProviderStatus,
  getSingleProviderStats,
  getAllProviders
};

// src/modules/provider/provider.controller.ts
var createProvider = async (req, res) => {
  console.log("Cookies:", req.headers.cookie);
  console.log("User:", req.user);
  const user = req.user;
  if (!user) {
    return res.status(400).json({
      error: "unauthorized",
      message: "user not found in request"
    });
  }
  const result = await providerService.createProviderProfile(req.body, user.id);
  res.status(201).json({
    success: true,
    data: result
  });
};
var getProviderProfile2 = async (req, res) => {
  try {
    const result = await providerService.getProviderProfile();
    res.status(200).json(result);
  } catch (e) {
    res.status(400).json({
      error: "Get provider failed",
      details: e
    });
  }
};
var updateProviderStatus2 = async (req, res) => {
  try {
    const { id } = req.params;
    const { is_active } = req.body;
    const result = await providerService.updateProviderStatus(id, is_active);
    res.status(200).json({
      success: true,
      message: "Status updated successfully",
      data: result
    });
  } catch (err) {
    console.error(err);
    res.status(500).json({
      success: false,
      message: "Failed to update status"
    });
  }
};
var getProviderStatsForAdmin = async (req, res) => {
  try {
    const { id } = req.params;
    const stats = await providerService.getAllSystemStatsForAdmin();
    if (!stats) {
      return res.status(404).json({
        success: false,
        message: "Provider not found"
      });
    }
    res.status(200).json({
      success: true,
      data: stats
    });
  } catch (err) {
    console.error(err);
    res.status(500).json({
      success: false,
      message: "Internal Server Error"
    });
  }
};
var getAllProviders2 = async (req, res) => {
  try {
    const providers = await prisma.provider_Profile.findMany({});
    if (!providers || providers.length === 0) {
      return res.status(404).json({
        success: false,
        message: "No providers found"
      });
    }
    res.status(200).json({
      success: true,
      data: providers
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({
      success: false,
      message: "Internal Server Error"
    });
  }
};
var getMyDashboardStats = async (req, res) => {
  try {
    const providerId = req.user?.id || req.session?.user?.id;
    if (!providerId) {
      return res.status(401).json({
        success: false,
        message: "\u0986\u09AA\u09A8\u09BF \u09B2\u0997\u0987\u09A8 \u0995\u09B0\u09BE \u09A8\u09C7\u0987! \u09B8\u09C7\u09B6\u09A8 \u09AA\u09BE\u0993\u09DF\u09BE \u09AF\u09BE\u09DF\u09A8\u09BF\u0964"
      });
    }
    console.log("\u09B8\u09C7\u09B6\u09A8 \u09A5\u09C7\u0995\u09C7 \u09AA\u09BE\u0993\u09DF\u09BE \u0986\u0987\u09A1\u09BF:", providerId);
    const stats = await providerService.getSingleProviderStats(providerId);
    res.status(200).json({
      success: true,
      data: stats
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};
var ProviderController = {
  createProvider,
  getProviderProfile: getProviderProfile2,
  getProviderStatsForAdmin,
  updateProviderStatus: updateProviderStatus2,
  getAllProviders: getAllProviders2,
  getMyDashboardStats
};

// src/lib/auth.ts
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";
import nodemailer from "nodemailer";
var transporter = nodemailer.createTransport({
  host: "smtp.gmail.com",
  port: 587,
  secure: false,
  auth: {
    user: process.env.APP_USER,
    pass: process.env.APP_PASS
  }
});
var isProduction = process.env.NODE_ENV?.toLowerCase() === "production";
console.log("Is it Production?", isProduction);
var auth = betterAuth({
  basePath: "/api/auth",
  database: prismaAdapter(prisma, {
    provider: "postgresql"
  }),
  session: {
    cookieCache: {
      enabled: true,
      maxAge: 5 * 60
    }
  },
  advanced: {
    cookiePrefix: "better-auth",
    useSecureCookies: process.env.NODE_ENV === "production",
    crossSubDomainCookies: {
      enabled: false
    },
    disableCSRFCheck: true,
    defaultCookieAttributes: {
      secure: isProduction,
      sameSite: isProduction ? "none" : "lax",
      httpOnly: true
    },
    trustProxy: true
  },
  trustedOrigins: [
    "https://*.vercel.app"
  ],
  user: {
    additionalFields: {
      role: {
        type: "string",
        defaultValue: "USER"
      },
      phone: {
        type: "string"
      },
      status: {
        type: "string",
        defaultValue: "ACTIVE"
      }
    }
  },
  emailAndPassword: {
    enabled: true,
    autoSignIn: false,
    requireEmailVerification: true
  },
  emailVerification: {
    sendOnSignUp: true,
    autoSignInAfterVerification: true,
    sendVerificationEmail: async ({ user, token }) => {
      try {
        const sendVerificationUrl = `${process.env.APP_URL}/verify-email?token=${token}`;
        const info = await transporter.sendMail({
          from: `"Foodhub" <${process.env.APP_USER}>`,
          to: user.email,
          subject: "Please Verify Your Email",
          text: `Verify your email here: ${sendVerificationUrl}`,
          html: `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>Email Verification</title>
</head>
<body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="padding:20px 0;">
<tr>
<td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 4px 10px rgba(0,0,0,0.05);">

<tr>
<td align="center" style="background:#16a34a;padding:20px;">
<h1 style="color:#ffffff;margin:0;">\u{1F37D}\uFE0F FoodHub</h1>
</td>
</tr>

<tr>
<td style="padding:30px;">
<h2 style="margin-top:0;color:#333;">Verify Your Email Address</h2>

<p style="color:#555;font-size:15px;line-height:1.6;">
Thanks for signing up with <strong>FoodHub</strong>!
Please confirm your email address to activate your account.
</p>

<p style="text-align:center;margin:30px 0;">
<a href="${sendVerificationUrl}"
style="background:#16a34a;color:#ffffff;text-decoration:none;
padding:12px 25px;border-radius:5px;font-size:16px;display:inline-block;">
Verify Email
</a>
</p>

<p style="word-break:break-all;color:#16a34a;font-size:13px;">
${sendVerificationUrl}
</p>

<p style="color:#999;font-size:12px;margin-top:30px;">
If you did not create an account, you can safely ignore this email.
</p>

</td>
</tr>

<tr>
<td align="center" style="background:#f9fafb;padding:15px;font-size:12px;color:#888;">
\xA9 ${(/* @__PURE__ */ new Date()).getFullYear()} FoodHub. All rights reserved.
</td>
</tr>

</table>
</td>
</tr>
</table>
</body>
</html>`
        });
        console.log("Verification email sent:", info.messageId);
      } catch (err) {
        console.error("Email sending failed:", err);
        throw err;
      }
    }
  }
});

// src/middlewares/auth.ts
var auth2 = (...roles) => {
  return async (req, res, next) => {
    try {
      const session = await auth.api.getSession({
        headers: { cookie: req.headers.cookie || "" }
      });
      console.log("HEADERS \u{1F449}", req.headers);
      console.log("COOKIE \u{1F449}", req.headers.cookie);
      console.log("SESSION \u{1F449}", session);
      console.log("SESSION USER \u{1F449}", session?.user);
      if (!session) {
        return res.status(401).json({
          success: false,
          message: "You are not authorised"
        });
      }
      if (!session.user.emailVerified) {
        return res.status(403).json({
          success: false,
          message: "Email verification requiered ,plz verify your email "
        });
      }
      req.user = {
        id: session.user.id,
        email: session.user.email,
        name: session.user.name,
        role: session.user.role,
        emailVerified: session.user.emailVerified
      };
      if (roles.length && !roles.includes(req.user.role)) {
        return res.status(403).json({
          success: false,
          message: "forbidden ! You don't have a permission to access this resourcess !"
        });
      }
      next();
    } catch (err) {
      next(err);
    }
  };
};
var auth_default = auth2;

// src/modules/provider/provider.router.ts
var router = express.Router();
router.get(
  "/dashboard-stats",
  // auth(UserRole.ADMIN || UserRole.PROVIDER),
  ProviderController.getProviderStatsForAdmin
);
router.get(
  "/getprofile",
  ProviderController.getProviderProfile
);
router.get(
  "/allproviders",
  ProviderController.getAllProviders
);
router.post(
  "/create",
  auth_default(UserRole.PROVIDER),
  ProviderController.createProvider
);
router.get("/getmy/dashboard-stats", ProviderController.getMyDashboardStats);
router.patch(
  "/update-status/:id",
  auth_default(UserRole.ADMIN),
  // যদি অ্যাডমিন প্রটেকশন থাকে
  ProviderController.updateProviderStatus
);
var postRouter = router;

// src/app.ts
import { toNodeHandler } from "better-auth/node";
import cors from "cors";

// src/modules/meals/meals.route.ts
import express2 from "express";

// src/modules/meals/meals.services.ts
var createMeal = async (userId, data) => {
  const provider = await prisma.provider_Profile.findUnique({
    where: { user_id: userId }
  });
  if (!provider) {
    throw new Error("Provider profile not found");
  }
  const category = await prisma.categories.findUnique({
    where: { id: data.category_id }
  });
  const result = await prisma.meals.create({
    data: {
      name: data.name,
      description: data.description,
      price: data.price,
      image_url: data.image_url,
      provider: {
        connect: { id: provider.id }
      },
      category: {
        connect: { id: data.category_id }
      }
    }
  });
  return result;
};
var getMyMeals = async (userId) => {
  const provider = await prisma.provider_Profile.findUnique({
    where: { user_id: userId }
    // আপনার স্কিমা অনুযায়ী user_id বা id
  });
  if (!provider) {
    throw new Error("\u09AA\u09CD\u09B0\u09CB\u09AD\u09BE\u0987\u09A1\u09BE\u09B0 \u09AA\u09CD\u09B0\u09CB\u09AB\u09BE\u0987\u09B2 \u09AA\u09BE\u0993\u09DF\u09BE \u09AF\u09BE\u09DF\u09A8\u09BF!");
  }
  const meals = await prisma.meals.findMany({
    where: {
      provider_id: provider.id
      // আসল প্রোভাইডার আইডি ব্যবহার হচ্ছে
    },
    include: {
      category: true
    }
  });
  return meals;
};
var getAllPublicMeals = async () => {
  const meals = await prisma.meals.findMany({
    where: {
      status: "AVAILABLE"
    },
    include: {
      provider: {
        select: {
          restaurant_name: true,
          address: true
        }
      },
      category: { select: { name: true } }
    }
  });
  return meals;
};
var getSingleMeal = async (id) => {
  const meal = await prisma.meals.findUnique({
    where: { id },
    include: {
      provider: {
        select: {
          restaurant_name: true,
          address: true
        }
      },
      category: {
        select: { name: true }
      }
    }
  });
  if (!meal) {
    throw new Error("Meal not found");
  }
  return meal;
};
var MealsService = {
  createMeal,
  getMyMeals,
  getAllPublicMeals,
  getSingleMeal
};

// src/modules/meals/meals.controller.ts
var createMeal2 = async (req, res) => {
  try {
    const userId = req.user.id;
    const result = await MealsService.createMeal(userId, req.body);
    res.status(201).json({
      success: true,
      messege: "Meal created successfully ",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: error.message
    });
  }
};
var getMyMeals2 = async (req, res) => {
  try {
    const providerId = req.params.providerId;
    const result = await MealsService.getMyMeals(providerId);
    res.status(200).json({
      success: true,
      messege: "Meal created successfully",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: error.message
    });
  }
};
var getAllPublicMeals2 = async (req, res) => {
  try {
    const result = await MealsService.getAllPublicMeals();
    res.status(200).json({
      success: true,
      message: "Meals retieved successfully ",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: error.message
    });
  }
};
var getSingleMeal2 = async (req, res) => {
  const { id } = req.params;
  const result = await MealsService.getSingleMeal(id);
  res.status(200).json({
    success: true,
    data: result
  });
};
var MealsController = {
  createMeal: createMeal2,
  getMyMeals: getMyMeals2,
  getAllPublicMeals: getAllPublicMeals2,
  getSingleMeal: getSingleMeal2
};

// src/modules/meals/meals.route.ts
var router2 = express2.Router();
router2.post(
  "/create",
  auth_default(UserRole.PROVIDER),
  MealsController.createMeal
);
router2.get(
  "/my-meals/:providerId",
  // auth(UserRole.PROVIDER || UserRole.USER),
  MealsController.getMyMeals
);
router2.get(
  "/",
  MealsController.getAllPublicMeals
);
router2.get(
  "/:id",
  MealsController.getSingleMeal
);
var MealsRoutes = router2;

// src/modules/categories/categories.router.ts
import express3 from "express";

// src/modules/categories/categories.service.ts
var createCategory = async (name) => {
  const result = await prisma.categories.create({
    data: { name }
  });
  return result;
};
var getAllCategories = async () => {
  return prisma.categories.findMany({
    orderBy: { name: "asc" }
  });
};
var CategoriesService = {
  createCategory,
  getAllCategories
};

// src/modules/categories/categories.controller.ts
var createCategory2 = async (req, res) => {
  try {
    const result = await CategoriesService.createCategory(req.body.name);
    res.status(201).json({ success: true, data: result });
  } catch (err) {
    res.status(400).json({ success: false, message: "Category creation failed" });
  }
};
var getCategories = async (_req, res) => {
  const result = await CategoriesService.getAllCategories();
  res.json({ success: true, data: result });
};
var CategoriesController = {
  createCategory: createCategory2,
  getCategories
};

// src/modules/categories/categories.router.ts
var router3 = express3.Router();
router3.post(
  "/",
  auth_default(UserRole.ADMIN),
  CategoriesController.createCategory
);
router3.get(
  "/",
  CategoriesController.getCategories
);
var categoriesRouter = router3;

// src/modules/orders/order.route.ts
import express4 from "express";

// src/modules/orders/order.services.ts
var createOrder = async (userId, payload) => {
  const { items, delivery_address } = payload;
  if (!items || items.length === 0) {
    throw new Error("Order items required");
  }
  if (!delivery_address) {
    throw new Error("Delivery address required");
  }
  let totalPrice = 0;
  const orderItemsData = [];
  for (const item of items) {
    const meal = await prisma.meals.findUnique({
      where: { id: item.mealId }
    });
    if (!meal) throw new Error("Meal not found");
    totalPrice += Number(meal.price) * item.quantity;
    orderItemsData.push({
      meal_id: meal.id,
      customer_id: userId,
      quantity: item.quantity,
      price_at_order: meal.price
    });
  }
  const order = await prisma.orders.create({
    data: {
      customer_id: userId,
      delivery_address,
      // 👈 make sure this is a string
      total_price: totalPrice,
      orderItems: { create: orderItemsData }
    },
    include: { orderItems: true }
  });
  return order;
};
var getMyOrders = async (userId) => {
  return prisma.orders.findMany({
    where: {
      customer_id: userId
    },
    include: {
      orderItems: {
        include: {
          meal: {
            select: {
              name: true,
              price: true
            }
          }
        }
      }
    }
  });
};
var getAllOrders = async () => {
  return prisma.orders.findMany({
    include: {
      orderItems: true
    }
  });
};
var OrdersService = {
  createOrder,
  getMyOrders,
  getAllOrders
};

// src/modules/orders/order.controller.ts
var createOrder2 = async (req, res) => {
  try {
    const userId = req.user.id;
    const result = await OrdersService.createOrder(userId, req.body);
    res.status(201).json({
      success: true,
      message: "Order placed successfully",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: error.message
    });
  }
};
var getMyOrders2 = async (req, res) => {
  try {
    const userId = req.user.id;
    const result = await OrdersService.getMyOrders(userId);
    res.json({
      success: true,
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: error.message
    });
  }
};
var getAllOrders2 = async (_req, res) => {
  try {
    const result = await OrdersService.getAllOrders();
    res.json({
      success: true,
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: error.message
    });
  }
};
var OrdersController = {
  createOrder: createOrder2,
  getMyOrders: getMyOrders2,
  getAllOrders: getAllOrders2
};

// src/modules/orders/order.route.ts
var router4 = express4.Router();
router4.post(
  "/",
  auth_default(UserRole.USER),
  OrdersController.createOrder
);
router4.get(
  "/my-orders",
  auth_default(UserRole.USER),
  OrdersController.getMyOrders
);
router4.get(
  "/",
  auth_default(UserRole.ADMIN),
  OrdersController.getAllOrders
);
var OrdersRoutes = router4;

// src/modules/provider-order/providerOrder.route.ts
import express5 from "express";

// src/modules/provider-order/providerOrder.service.ts
var getProviderOrders = async (userId) => {
  const provider = await prisma.provider_Profile.findUnique({
    where: { user_id: userId }
  });
  if (!provider) {
    throw new Error("Provider profile not found");
  }
  const orderItems = await prisma.order_items.findMany({
    where: {
      meal: {
        provider_id: provider.id
      }
    },
    include: {
      orders: true,
      meal: {
        select: {
          name: true,
          price: true
        }
      },
      customer: {
        select: {
          name: true,
          email: true
        }
      }
    }
  });
  return orderItems;
};
var allowedStatusFlow = {
  PLACED: [OrderStatus.PREPARING],
  PREPARING: [OrderStatus.READY]
};
var updateOrderStatus = async (providerUserId, orderId, newStatus) => {
  const provider = await prisma.provider_Profile.findUnique({
    where: { user_id: providerUserId }
  });
  if (!provider) {
    throw new Error("Provider profile not found");
  }
  const order = await prisma.orders.findUnique({
    where: { id: orderId },
    include: {
      orderItems: {
        include: {
          meal: true
        }
      }
    }
  });
  if (!order) {
    throw new Error("Order not found");
  }
  const isProviderOrder = order.orderItems.some(
    (item) => item.meal.provider_id === provider.id
  );
  if (order.status === OrderStatus.READY) {
    throw new Error("Order already completed");
  }
  if (!isProviderOrder) {
    throw new Error("You are not allowed to update this order");
  }
  const allowedNext = allowedStatusFlow[order.status];
  if (!allowedNext || !allowedNext.includes(newStatus)) {
    throw new Error(
      `Invalid status transition from ${order.status} to ${newStatus}`
    );
  }
  const updatedOrder = await prisma.orders.update({
    where: { id: orderId },
    data: { status: newStatus }
  });
  return updatedOrder;
};
var ProviderOrderService = {
  getProviderOrders,
  updateOrderStatus
};

// src/modules/provider-order/providerOrder.controller.ts
var getMyOrders3 = async (req, res) => {
  try {
    const userId = req.user.id;
    const result = await ProviderOrderService.getProviderOrders(userId);
    res.status(200).json({
      success: true,
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: error.message
    });
  }
};
var updateOrderStatus2 = async (req, res) => {
  try {
    const { orderId } = req.params;
    const { status } = req.body;
    const providerId = req.user.id;
    const result = await ProviderOrderService.updateOrderStatus(
      providerId,
      orderId,
      status
    );
    res.status(200).json({
      success: true,
      message: "Order status updated successfully",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: error.message
    });
  }
};
var ProviderOrderController = {
  getMyOrders: getMyOrders3,
  updateOrderStatus: updateOrderStatus2
};

// src/modules/provider-order/providerOrder.route.ts
var router5 = express5.Router();
router5.get(
  "/",
  auth_default(UserRole.PROVIDER),
  ProviderOrderController.getMyOrders
);
router5.patch(
  "/:orderId/status",
  auth_default(UserRole.PROVIDER),
  ProviderOrderController.updateOrderStatus
);
var ProviderOrderRoutes = router5;

// src/modules/admin/adminOrders.route.ts
import express6 from "express";

// src/modules/admin/adminOrders.service.ts
var getAllOrders3 = async () => {
  return await prisma.orders.findMany({
    include: {
      orderItems: {
        include: {
          meal: {
            select: {
              name: true,
              price: true
            }
          }
        }
      }
    },
    orderBy: {
      created_at: "desc"
    }
  });
};
var updateOrderStatus3 = async (orderId, status) => {
  return await prisma.orders.update({
    where: { id: orderId },
    data: { status }
  });
};
var getDashboardStats = async () => {
  const [
    totalUsers,
    totalProviders,
    totalMeals,
    totalOrders,
    revenue,
    orderStats
  ] = await Promise.all([
    prisma.user.count(),
    prisma.provider_Profile.count(),
    prisma.meals.count(),
    prisma.orders.count(),
    prisma.orders.aggregate({
      _sum: {
        total_price: true
      }
    }),
    prisma.orders.groupBy({
      by: ["status"],
      _count: {
        _all: true
      }
    })
  ]);
  return {
    totalUsers,
    totalProviders,
    totalMeals,
    totalOrders,
    totalRevenue: revenue._sum.total_price || 0,
    ordersByStatus: orderStats
  };
};
var AdminOrdersService = {
  getAllOrders: getAllOrders3,
  updateOrderStatus: updateOrderStatus3,
  getDashboardStats
};

// src/modules/admin/adminOrders.controller.ts
var getAllOrders4 = async (req, res) => {
  const result = await AdminOrdersService.getAllOrders();
  res.status(200).json({
    success: true,
    data: result
  });
};
var updateOrderStatus4 = async (req, res) => {
  const { id } = req.params;
  const { status } = req.body;
  const result = await AdminOrdersService.updateOrderStatus(id, status);
  res.status(200).json({
    success: true,
    message: "Order status updated successfully",
    data: result
  });
};
var getDashboardStats2 = async (req, res) => {
  const stats = await AdminOrdersService.getDashboardStats();
  res.status(200).json({
    success: true,
    data: stats
  });
};
var AdminOrdersController = {
  getAllOrders: getAllOrders4,
  updateOrderStatus: updateOrderStatus4,
  getDashboardStats: getDashboardStats2
};

// src/modules/admin/adminOrders.route.ts
var router6 = express6.Router();
router6.get(
  "/orders",
  auth_default(UserRole.ADMIN),
  AdminOrdersController.getAllOrders
);
router6.patch(
  "/orders/:id/status",
  auth_default(UserRole.ADMIN),
  AdminOrdersController.updateOrderStatus
);
router6.get(
  "/dashboard-stats",
  auth_default(UserRole.ADMIN),
  AdminOrdersController.getDashboardStats
);
var AdminOrdersRoutes = router6;

// src/modules/user-management/adminUser.router.ts
import express7 from "express";

// src/modules/user-management/adminUser.service.ts
var getAllUsers = async () => {
  return prisma.user.findMany({
    select: {
      id: true,
      name: true,
      email: true,
      role: true,
      status: true,
      createdAt: true
    }
  });
};
var updateUserRole = async (userId, role) => {
  return prisma.user.update({
    where: { id: userId },
    data: { role }
  });
};
var updateUserStatus = async (userId, status) => {
  return prisma.user.update({
    where: { id: userId },
    data: { status }
  });
};
var AdminUserService = {
  getAllUsers,
  updateUserRole,
  updateUserStatus
};

// src/modules/user-management/adminUser.controller.ts
var getAllUsers2 = async (_req, res) => {
  const users = await AdminUserService.getAllUsers();
  res.json({
    success: true,
    data: users
  });
};
var updateUserRole2 = async (req, res) => {
  const { id } = req.params;
  const { role } = req.body;
  const user = await AdminUserService.updateUserRole(id, role);
  res.json({
    success: true,
    message: "User role updated",
    data: user
  });
};
var updateUserStatus2 = async (req, res) => {
  const { id } = req.params;
  const { status } = req.body;
  const user = await AdminUserService.updateUserStatus(id, status);
  res.json({
    success: true,
    message: "User status updated",
    data: user
  });
};
var AdminUserController = {
  getAllUsers: getAllUsers2,
  updateUserRole: updateUserRole2,
  updateUserStatus: updateUserStatus2
};

// src/modules/user-management/adminUser.router.ts
var router7 = express7.Router();
router7.get(
  "/users",
  auth_default(UserRole.ADMIN),
  AdminUserController.getAllUsers
);
router7.patch(
  "/users/:id/role",
  auth_default(UserRole.ADMIN),
  AdminUserController.updateUserRole
);
router7.patch(
  "/users/:id/status",
  auth_default(UserRole.ADMIN),
  AdminUserController.updateUserStatus
);
var adminUserRouter = router7;

// src/modules/reviews/reviews.route.ts
import express8 from "express";

// src/modules/reviews/reviews.service.ts
var createReview = async (userId, mealId, data) => {
  const existing = await prisma.reviews.findFirst({
    where: {
      customer_id: userId,
      meal_id: mealId
    }
  });
  if (existing) {
    throw new Error("You have already reviewed this meal");
  }
  const review = await prisma.reviews.create({
    data: {
      customer_id: userId,
      meal_id: mealId,
      rating: data.rating,
      comment: data.comment
    }
  });
  return review;
};
var getReviewsByMeal = async (mealId) => {
  const reviews = await prisma.reviews.findMany({
    where: { meal_id: mealId },
    include: {
      customer: {
        select: {
          name: true,
          email: true
        }
      }
    }
  });
  return reviews;
};
var getReviewsProviderByMeal = async (mealId, providerId) => {
  const meal = await prisma.meals.findUnique({
    where: { id: mealId },
    select: { provider_id: true }
  });
  if (!meal) throw new Error("Meal not found");
  if (meal.provider_id !== providerId) throw new Error("Not authorized to view reviews");
  const reviews = await prisma.reviews.findMany({
    where: { meal_id: mealId },
    include: {
      customer: { select: { name: true, email: true } }
    },
    orderBy: { created_at: "desc" }
  });
  return reviews;
};
var getAllReviewsbyAdmin = async () => {
  const reviews = await prisma.reviews.findMany({
    include: {
      customer: { select: { name: true, email: true } },
      meal: { select: { name: true, provider_id: true } }
    },
    orderBy: { created_at: "desc" }
  });
  return reviews;
};
var deleteReviewbyAdmin = async (reviewId) => {
  return await prisma.reviews.delete({
    where: { id: reviewId }
  });
};
var ReviewsService = {
  createReview,
  getReviewsByMeal,
  getReviewsProviderByMeal,
  getAllReviewsbyAdmin,
  deleteReviewbyAdmin
};

// src/modules/reviews/reviews.controller.ts
var createReview2 = async (req, res) => {
  try {
    const userId = req.user.id;
    const mealId = req.params.mealId;
    const { rating, comment } = req.body;
    const review = await ReviewsService.createReview(userId, mealId, {
      rating,
      comment
    });
    res.json({ success: true, review });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};
var getReviews = async (req, res) => {
  try {
    const mealId = req.params.mealId;
    const reviews = await ReviewsService.getReviewsByMeal(mealId);
    res.json({ success: true, reviews });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};
var getReviewsProviderByMeal2 = async (req, res) => {
  try {
    const mealId = req.params.mealId;
    const providerId = req.user.id;
    const reviews = await ReviewsService.getReviewsProviderByMeal(mealId, providerId);
    res.json({ success: true, reviews });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};
var getAllReviewsbyAdmin2 = async (req, res) => {
  try {
    const reviews = await ReviewsService.getAllReviewsbyAdmin();
    res.json({ success: true, reviews });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};
var deleteReviewbyAdmin2 = async (req, res) => {
  try {
    const reviewId = req.params.reviewId;
    await ReviewsService.deleteReviewbyAdmin(reviewId);
    res.json({ success: true, message: "Review deleted" });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};
var ReviewsController = {
  createReview: createReview2,
  getReviews,
  getReviewsProviderByMeal: getReviewsProviderByMeal2,
  deleteReviewbyAdmin: deleteReviewbyAdmin2,
  getAllReviewsbyAdmin: getAllReviewsbyAdmin2
};

// src/modules/reviews/reviews.route.ts
var router8 = express8.Router();
router8.post(
  "/:mealId",
  auth_default(UserRole.USER),
  ReviewsController.createReview
);
router8.get("/:mealId", ReviewsController.getReviews);
router8.get("/provider/reviews/:mealId", auth_default(UserRole.PROVIDER), ReviewsController.getReviewsProviderByMeal);
router8.get("/admin/reviews", auth_default(UserRole.ADMIN), ReviewsController.getAllReviewsbyAdmin);
router8.delete("/admin/reviews/:reviewId", auth_default(UserRole.ADMIN), ReviewsController.deleteReviewbyAdmin);
var ReviewsRoutes = router8;

// src/app.ts
var app = express9();
app.set("trust proxy", true);
var allowedOrigins = [
  process.env.APP_URL || "http://localhost:3000",
  process.env.PROD_APP_URL
].filter(Boolean);
app.use(
  cors({
    origin: (origin, callback) => {
      if (!origin) return callback(null, true);
      const isAllowed = allowedOrigins.includes(origin) || /^https:\/\/foodhub-client.*\.vercel\.app$/.test(origin) || /^https:\/\/.*\.vercel\.app$/.test(origin);
      if (isAllowed) {
        callback(null, true);
      } else {
        callback(new Error(`Origin ${origin} not allowed by CORS`));
      }
    },
    credentials: true,
    methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
    allowedHeaders: ["Content-Type", "Authorization", "Cookie"],
    exposedHeaders: ["Set-Cookie"]
  })
);
app.use(express9.json());
app.all(/\/api\/auth\/.*/, toNodeHandler(auth));
app.use("/api/provider", postRouter);
app.use("/api/meals", MealsRoutes);
app.use("/api/categories", categoriesRouter);
app.use("/api/orders", OrdersRoutes);
app.use("/api/provider/orders", ProviderOrderRoutes);
app.use("/api/admin/order-management", AdminOrdersRoutes);
app.use("/api/reviews", ReviewsRoutes);
app.use("/api/admin/user-management", adminUserRouter);
app.get("/", (req, res) => {
  res.send("Hello world !");
});
var app_default = app;

// src/index.ts
var PORT = process.env.PORT || 5e3;
async function main() {
  try {
    await prisma.$connect();
    console.log("connected to the database successfully .");
    app_default.listen(PORT, () => {
      console.log(`server is running on  http://localhost:${PORT}`);
    });
  } catch (error) {
    console.log("an error occurred", error);
    await prisma.$disconnect();
    process.exit(1);
  }
}
main();
var index_default = app_default;
export {
  index_default as default
};
